### ISSUE TITLE
merge 3.2 branch, make default

### ISSUE THREAD

**Issue by blockspacer** [Zylann/godot_voxel#113]
major update, Godot 3.2!
related to https://godotengine.org/article/here-comes-godot-3-2

**Comment by tinmanjuggernaut** [comment]
What is the issue? What do you suggest be merged? We already have VT master for 3.2 which is the default people should use.

**Comment by Zylann** [comment]
There is no merge to do since the master branch of this repository has been the main one so far, so in a sense master *is* the one made for 3.2.

That said, we could make a 3.2 branch like we have a 3.1. This would be especially interesting considering the next Godot version is 4.0, so things are going to get broken soon with the vulkan branch merging.

**Comment by tinmanjuggernaut** [comment]
@Zylann Do you intend to backport all the recent features to the 3.1 branch? And continue to maintain that in the future? Or just have a snapshot of a branch that did work with the older version.

**Comment by Zylann** [comment]
@tinmanjuggernaut the idea would be to snapshot the moment 3.2 was released, at least. However I'm not sure I have time to maintain and backport these branches though.

**Comment by blockspacer** [comment]
> We already have VT master for 3.2 which is the default people should use.

Good news.

> maintain and backport these branches though.
> snapshot the moment 3.2 was released
> things are going to get broken soon with the vulkan branch

Separate issue may be created for backport branches, if needed.
