### ISSUE TITLE
Compile Error on Godot 3 (master) related to PoolVector

### ISSUE THREAD

**Issue by HummusSamurai** [Zylann/godot_voxel#12]
The issue with opensimplex (https://github.com/Zylann/godot_opensimplex/issues/2) was solved by the PR (thanks @Xrayez), and Godot now compiles with opensimplex.

However now I get the following error when compiling voxel with Godot 3 master, both when compiling with the opensimplex module and alone.

> modules/voxel/voxel_mesher_smooth.cpp: In function 'void copy_to(PoolVector<T>&, Vector<T>&)':
> modules/voxel/voxel_mesher_smooth.cpp:54:2: error: need 'typename' before 'PoolVector<T>::Write' because 'PoolVector<T>' is a dependent scope
>   PoolVector<T>::Write w = to.write();
>   ^~~~~~~~~~~~~
> 

Full pastebin of the errors: https://pastebin.com/UnXu7g6R

I think I saw a discussion about PoolVector in some PR recently, but I can't seem to find it again.

Thanks again and I am looking forward to making this work!

**Comment by Zylann** [comment]
It's really easy to fix, the solution is in the errors (litterally)

**Comment by Zylann** [comment]
I submitted a fix

**Comment by HummusSamurai** [comment]
Success! The engine compiles with opensimplex, voxel, and hterrain!

I can now finally test some terrain :3 
I'll let you know how it goes.

**Comment by HummusSamurai** [comment]
I launched the voxelgame project and I'm getting an error in the editor when I try to launch:

Invalid call. Nonexistent function 'set_cube_geometry' in base 'Voxel'

Line 15 in voxelmap.gd

**Comment by Zylann** [comment]
uh... well you can comment out most of this script actually, what it does is done in .tscn already now :)

**Comment by HummusSamurai** [comment]
@Zylann I commented out the lines that caused errors, and it works even after I instanced my own character controller.

Unfortunately there are no collisions, neither the kinematicbody player nor his bullets are colliding with anything.

The commented lines were definitely needed, as the game looks rather bare now. But it's progress!

**Comment by Zylann** [comment]
The commented lines were not doing any collision. In fact there are no collisions because I need to remake them differently, also i'm waiting for this: https://github.com/godotengine/godot/pull/10013

**Comment by HummusSamurai** [comment]
Oh well then I guess I'll wait :D 
But it's already impressive to see right now (although I didn't find an option for smooth voxels anywhere).

Also I tried the heightmap and it keeps refusing to import the heightmaps I'm testing, even though the resolution is fine and I'm pretty sure I have the color settings correct also. Do you have any pointers?

**Comment by Zylann** [comment]
Smooth voxels are supported, but aren't exposed well editor-side.
The idea is that you have to generate voxel data in the channel `Voxel.CHANNEL_ISOLEVEL` instead of `Voxel.CHANNEL_TYPE`. The smooth mesher doesn't use VoxelLibrary at all though, and the output will be texture-less, but it's a start^^ 
I need to write some documentation at some point, because you can also write your own voxel generator by inheriting `VoxelProvider`, and putting it in the `VoxelTerrain` (in the example I have set `VoxelProviderTest`, which generates waves in the CHANNEL_TYPE channel).

If you want to ask stuff about `HeightMap`, you should open an issue there: https://github.com/Zylann/godot_heightmap_module/issues

**Comment by Zylann** [comment]
The script error should be fixed now
