### ISSUE TITLE
Missed smooth_trimesh_collision property

### ISSUE THREAD

**Issue by wacyym** [Zylann/godot_voxel#145]
Hello!
Firstly, thanks a lot for another great godot plugin!

Im using latest prebuild binary (3.2.2rc+cd8d43), and noticed that is missed property in project settings named "smooth trimesh collision" (Project Settings/Physics/3d/). Why i cant use this option with voxel plugin?

**Comment by wacyym** [comment]
Oh, i added smooth_trimesh_collision manually, and got huge delay for editing terrain - similar effect while using Vsync (issue #48)

**Comment by tinmanjuggernaut** [comment]
In stock Godot 3.2.1 I don't see any Project Settings / Physics / 3D / Smooth Trimesh Collision. So I wouldn't expect there to be one in the 3.2.2rc binary either unless it was added between the commits. You are likely encountering an upstream issue with the engine itself.

Can you find it in the stock binary?

**Comment by wacyym** [comment]
Yes, In stock Godot i see this property.
It was be added here: https://github.com/godotengine/godot/issues/21341 since Godot 3.1

**Comment by tinmanjuggernaut** [comment]
There's nothing in that issue, or the corresponding PR that changed the engine code that mentions or adds an option to Project Settings. I don't see it in my project settings for my build or stock Godot 3.2.1. Can you take a screenshot of it in your project settings in stock Godot? 

As for the functionality, do you have an object that is falling through the terrain? Or an object that bounces as it crosses the faces of the terrain? That's what that issue was for. I've not experienced either with voxel tools.

**Comment by Zylann** [comment]
I searched the entire docs for this property and could not find it.
https://docs.godotengine.org/en/stable/search.html?q=smooth_trimesh_collision&check_keywords=yes&area=default

**Comment by Zylann** [comment]
Closing since this because it's a project setting.
