### ISSUE TITLE
 Where is the placed cube

### ISSUE THREAD

**Issue by KylaCpper** [Zylann/godot_voxel#155]
I am using this to make a game similar to minecraft，
But I found that when I place a cube
like this
`

       var vt := get_voxel_tool();
       vt.mode = VoxelTool.MODE_ADD;
       vt.set_voxel(Vector3(x,y,z),1);`
Then he showed it as I wanted

But once I set the “viewer path“
The terrain is like entering a loop，
When I stay away from him, and then go back,
All changes I placed and destroyed before are initialized
Then I see the console appear
Requesting save of block (x, y, z)  ---（The location I changed before） 

Is it something I did wrong, or I need to re-operate the previous operation every time I enter a new area

**Comment by nonchip** [comment]
> All changes I placed and destroyed before are initialized

sounds like you're using a Generator instead of a Stream?

you should use something like a `VoxelStreamRegionFiles` to store your map in, and then set its "Fallback Stream" to the terrain generator you used before. that way it will use the directory you put in the stream's configuration to save your changes, and the generator to make new chunks if you travel somewhere the save doesn't have any data.

**Comment by KylaCpper** [comment]
> > All changes I placed and destroyed before are initialized
> 
> sounds like you're using a Generator instead of a Stream?
> 
> you should use something like a `VoxelStreamRegionFiles` to store your map in, and then set its "Fallback Stream" to the terrain generator you used before. that way it will use the directory you put in the stream's configuration to save your changes (or everything if you enable "Save Fallback Output", which makes the file way bigger because it saves unmodified chunks but could speed up chunk generation if your generator is too slow), and the generator to make new chunks if you travel somewhere the save doesn't have any data.

now I get it
