### ISSUE TITLE
Multiple Textures for Triplanar Mapping

### ISSUE THREAD

**Issue by kicknbrit** [Zylann/godot_voxel#159]
Hi I was wondering if there is any way to use multiple textures for triplanar mapping on a VoxelLodTerrain mesh?
Like for example, grass blocks and dirt blocks that are stored in a texture atlas and can be used depending on on the block type.

Thanks

**Comment by Zylann** [comment]
Yes? I mean, you can use whatever textures and techniques you want in shaders. You may want to be more specific about what you need from the voxel module.

**Comment by kicknbrit** [comment]
Sorry for the late reply. Yes to be a bit more clear I was wondering if there was anything exposed via a vertex attribute that I could use the set the texture for triplanar mapping. It appears not though. Any timeline for when this feature will get looked at? Thanks

**Comment by Zylann** [comment]
There is an open issue about this already https://github.com/Zylann/godot_voxel/issues/93

There is no timeline for this. I just need to figure out how to even bring texture data into the generated meshes. A simple way would be to use the `COLOR` attribute RGBA to splat 4 textures, but that's too limited, and that attribute is used already for Transvoxel stitching data. Besides, Godot doesn't allow us to put custom vertex attributes and the remaining ones are very scarce... so that's where the feature is at.

Also there are also issues about choosing different *materials*, which this time requires to have multiple surfaces within the mesh, and that's a different problem to tackle, see https://github.com/Zylann/godot_voxel/issues/104

**Comment by kicknbrit** [comment]
Okay well thanks for all the info. Looking forward to seeing this feature but I understand you must be swamped with things to do with this module so I will be patient. :)
