### ISSUE TITLE
The transparent block behind the transparent square does not display correctly.

### ISSUE THREAD

**Issue by KylaCpper** [Zylann/godot_voxel#204]
The glass inside the demo is placed next to the leaves, and then through the glass you can see the back of the leaves, and the leaves become completely transparent.

And when the glass is translucent, for example alpha = 100 in a different view of what's behind the glass is different in color.

**Comment by Zylann** [comment]
This?
![image](https://user-images.githubusercontent.com/1311555/97111577-803a0d80-16d7-11eb-9e07-97cebf326ae9.png)

Either it needs different configuration or there is something to tweak in the culling algorithm

**Comment by Zylann** [comment]
Might sound a bit unintuitive, but if you set leaves to be `transparent = false`, you get this result:

![image](https://user-images.githubusercontent.com/1311555/97112029-00fa0900-16da-11eb-9a5b-d28a6fdf2ec6.png)

**Comment by Zylann** [comment]
I settled on a variant of this:
Instead of transparency, voxels have a `transparency_index`. If two voxels should occlude a face they have in common, the face with the lowest `transparency_index` is culled. If both voxels have the same transparency index, both faces are culled.

This gives the following result:
![image](https://user-images.githubusercontent.com/1311555/97113218-c9428f80-16e0-11eb-8090-803a8e114c09.png)

**Comment by KylaCpper** [comment]
perfect
