### ISSUE TITLE
Higher view distance with Blocky Terrain

### ISSUE THREAD

**Issue by chibbi** [Zylann/godot_voxel#228]
So i haven't tried writing my own generator and stuff like that, because the Documentation for that doesn't exist yet (which is no problem, you are not working on this full time i understand).

For VoxelLODTerrain (the smooth terrain) exists the parameter "View Distance" as i far as i know.  Is there something similiar for the blocky terrain, or would i have to create my own generator to make that possible/ what would i have to do, to make that possible?

**Comment by Zylann** [comment]
In general, view distance is controlled by two things:
- The voxel node (VoxelTerrain here), on which you can configure the maximum range it can render with `max_view_distance`.
- The `VoxelViewer` node (usually parented under the player or camera), which has a setting for view distance, and it applies to all voxel nodes around it.

With `VoxelTerrain`, the resulting view distance is `min(viewer_distance, max_distance)`.

VoxelLodTerrain is a bit different because it actually doesn't support completely the `VoxelViewer` system. There is some pending work with view distances and streaming (it does not only apply to visuals, but also physics and availability of voxel data + supporting more than one viewer).

**Comment by chibbi** [comment]
Okay now i feel dumb because i didn't see either of those options.
What do you mean exactly, with "There is some pending work with view distances and streaming"?
Am i understanding it right, that "(it does not only apply to visuals, but also physics and availability of voxel data + supporting more than one viewer)" does not work yet?

**Comment by Zylann** [comment]
It mostly works with `VoxelTerrain`: you can have a `VoxelViewer` that only requests physics, voxels, and no visuals, and vice versa. It can also have multiple viewers. But `VoxelLodTerrain` cannot do that yet, and only support one viewer.
In addition to that, I think I will do a few more adjustments to how this system is designed, but at the moment it's low priority on my task list.

**Comment by chibbi** [comment]
Ah okay, thanks for the insight, i personally only plan on using VoxelTerrain, because building is much cooler with big blocks, than with smooth terrain.
