### ISSUE TITLE
HTML5 export

### ISSUE THREAD

**Issue by nadmaximus** [Zylann/godot_voxel#229]
Will html5 export ever be possible?

**Comment by Zylann** [comment]
Did you try it? If HTML5 exports support threads, it should work (otherwise performance will be atrocious, and I know web exports are already significantly slower). I'm not sure about streams though, since they essentially rely on files, so saving terrains might not work (generators dont need files). It might require a specialized stream, but I'm not experienced in web exports.

**Comment by nadmaximus** [comment]
I did try to build the export templates.  My build system was successful with Godot 3.2.  I was able to build Windows binaries for 3.2 with godot_voxel.  But, web exports with godot_voxel bails almost immediately.  I looked at the pre-built binaries here and did not see web export templates, so assumed it was simply not part of the project.

...According to the docs, HTML exports do not support threads in 3.2, and some alternative to using files for storage would be necessary.  It sounds like godot_voxel would not be performant in HTML5 at this time.  I am not going to try to make it work now.

Thank you for your attention.
