### ISSUE TITLE
Can't delete item from VoxelInstanceLibrary

### ISSUE THREAD

**Issue by slapin** [Zylann/godot_voxel#233]
This VoxelInstancer thing looks so great! Thanks a lot!
Wow, just need to figure out the controls though.

Found a problem: I can't delete item from embedded VoxelInstanceLibrary
created via editor GUI, option in menu doesn't work.
I don't plan to use instancing from editor at the moment though, but just to let you know.

**Comment by Zylann** [comment]
The inspector does not natively support this kind of operation, so like GridMap, it's been hacked by using property selection.
If you select the property name corresponding to an item, the menu item should work.

Unfortunately the property path returned by the inspector does not take sub-inspectors into account, so you have to first Edit the `VoxelInstanceLibrary` instead of doing it from a nested inspector.

Then I found a bug where I used `String::size()` instead of `String::length()`... it always lead to deleting item `0` even when it doesnt exist. Going to push a fix.

**Comment by Zylann** [comment]
Fixed removal in 9f11a288b0aba96ac16d7a50380dd70f78663313

**Comment by slapin** [comment]
Thanks a lot!
