### ISSUE TITLE
VoxelLodTerrain doesn't update on game run until clear and load of generator (using VoxelGeneratorGraph)

### ISSUE THREAD

**Issue by DevyHeavy** [Zylann/godot_voxel#275]
As the title says, unless I clear and then load the VoxelGeneratorGraph under generator for my VoxelLodTerrain object, then the changes do not apply when the game is run. I am not sure yet but this problem may stop the terrain from update in the editor as well, even if the Re-generate button is pressed.

This seems to have occurred after saving the VoxelGeneratorGraph as a different name by clicking Edit and then Save As. I am not sure though.

See the screencast below for the issue (I do not clear and load to solve in the screencast).

Version: v3.4.beta.mono.custom_build.8326b8b31
OS: Ubuntu 20.04.2 LTS x86_64

https://user-images.githubusercontent.com/28787282/120911629-cdf7fa80-c656-11eb-8783-41eeb5b9189e.mp4

I tried different names and relative project file paths but that doesn't seem to be the issue.

EDIT: Interesting, pressing the default button under Generator -> Resource -> Path puts the generator into its default state of behavior

EDIT2: Some more confusing behavior. If you edit a node in the graph, press play/run game, and alt+f4 out of the running game then the node parameters are still exposed; however, after changing the still exposed parameters the editor and game terrain does not update until selecting the VoxelGenerator, clicking the node again, and then changing the node's parameters.

**Comment by Zylann** [comment]
This is all very confusing, as I don't really know where to start testing this. It all seems to be that Godot is not saving the resource when it should (I hope this is not the same nonsense that's been plaguing my heightmap editor for years). Do you have specific reproduction steps that cause... a problem to occur?

If you rename a resource it can add some confusion due to messy behavior Godot has in these cases, so it would be good to rule this out, see if it happens without.

There is one odd behavior I know about, where editing stuff in the graph sometimes doesnt take effect when `Regenerate` is triggered, unless the `Update Previews` button is pressed first. I haven't found why yet.
There are also a few options in some sub-resources that don't immediately take effect as well, but that's because such resources are not emitting their `changed` signal, so the graph cannot know when to consider itself modified (which, btw, is something I really don't know how to tell Godot, there does not seem to be an API for that, other than doing everything through UndoRedo, which I use, but isn't always possible).

**Comment by Zylann** [comment]
Had a closer look at the code and I'll correct what I said:
this goes through UndoRedo, but not directly on the graph.

Internally, nodes of the graph are not classes. In order to be able to use the inspector like this, I create a wrapper which is then edited by the inspector. Godot does this trick too to let you edit arrays or dictionaries.
But that also means `UndoRedo` applies to that wrapper, and not the graph resource. So the change takes effect, but Godot does not know the graph changed (I still have no clue what `UndoRedo` does to make this happen). So the only way to force it to save the graph when you start the game, is to make a change that makes it happen, like moving a node around, or reassign it.

I don't know what I can do to solve this.

**Comment by DevyHeavy** [comment]
Should I/we make an issue in the Godot GitHub? Or am I misunderstanding, because it seems to be a feature/issue that we would like to have to allow plugins to work this way.

**Comment by Zylann** [comment]
It might not need an issue on Godot, but rather figure out if it can be solved with the API we have. It's been done before for the array and dictionary editors, I just dont understand how they do that (if they do)

**Comment by Zylann** [comment]
I did some digging and it turns out the array editor defines a marker method `_dont_undo_redo`. Its presence turns off UndoRedo from the inspector, letting the wrapper implement it itself. This is not documented, and that's what keyframe edition in AnimationPlayer also uses.
So I used that in a4565fd6dd9f36db282ab2c8fd8f86f5126c2e38. Let me know if it solves your problem.

**Comment by DevyHeavy** [comment]
Looks to have fixed the problem! The terrain takes on the correct parameters every time I run the game now.

Thanks for the help and work on this plugin.

Closing issue.
