### ISSUE TITLE
[QUESTION] How can I apply textures to voxel types?

### ISSUE THREAD

**Issue by toto-bird** [Zylann/godot_voxel#282]
**Problem**
I am trying to make a veloren/cube world/minecraft style game, and I can not figure out how to apply textures to cubes. I have looked at https://github.com/Zylann/voxelgame but I couldn't figure out how it applied textures to voxels, and how the custom meshes are stitched together.

**What I have tried**
I have created a cube shape in blender and applied textures there. However, when I try to generate a world using it, it crashes (Most likely because the meshes are not being combined).

**Comment by Zylann** [comment]
I still have to document the workflow, but the idea is that you should use a texture atlas.
In Blender, you should design voxel shapes within a cube of 1x1x1 where the lower corner is the origin. Then you UV-map each face using the atlas, but when exporting, you should only export the geometry, not the materials.
In Godot, you would have one material with the atlas, and it will be shared for every voxel, based on the `material ID` property on `Voxel` resources.

Do you get a crash because performance slows to a crawl? Or is it a different reason with errors?
Meshes are always combined, but if you make a giant mountain of dirt with dirt meshes with faces that don't exactly touch the sides of the 1x1x1 cube, then sides won't get culled and that can cause tremendous slowdown.

**Comment by toto-bird** [comment]
I have a cube made in blender where the origin is the center of the 1x1x1 cube.
It slows to the point where my mouse/keyboard/computer doesn't move at all.

Also, which corner should be the origin? bottom-east-west? something similar?

**Comment by Zylann** [comment]
It looks like this on my blender file
![image](https://user-images.githubusercontent.com/1311555/121908431-e89c3480-cd24-11eb-8ca4-4cfc71669bda.png)

**Comment by toto-bird** [comment]
I put the cube in what I think is the right position, but it still lags a ton. Also, I still have no idea how to apply the textures from the atlas.

**Comment by Zylann** [comment]
> I still have no idea how to apply the textures from the atlas.

Really, you just need to UV-map the model *as if it had that texture*. In Blender I opened the atlas in the Image Editor so i could see it while I UV-map the cube as in my previous screenshot. You can see the faces corresponding to atlas regions when I select them. So when I export that cube as a mesh, in Godot I can create a material with albedo texture set to the atlas, so when the mesh gets merged into a chunk, it will use the correct UVs. Materials don't directly come from the mesh precisely because it is *strongly* recommended to re-use them, so instead they are setup separately on the terrain node.
But generally, this needs improvements, and even more importantly, documentation, so I can stop having to explain this stuff over and over^^

> I put the cube in what I think is the right position, but it still lags a ton.

You may have to post a reproduction project then so I can see what's going on.

**Comment by toto-bird** [comment]
I figured it out (and by I figured it out, I mean I copied the cube object from the example I mentioned above, and followed this https://www.youtube.com/watch?v=48GNMXM-xms tutorial on it)

Quick, sort of unrelated question. Is it possible to give each tile a different modulate value when I'm generating the world?

**Comment by Zylann** [comment]
> Is it possible to give each tile a different modulate value when I'm generating the world?

This is not possible. That level of customization requires you to modify the mesher.

**Comment by toto-bird** [comment]
Alright. Thank you very much.
