### ISSUE TITLE
How to change the voxel size?

### ISSUE THREAD

**Issue by UAVwaffle** [Zylann/godot_voxel#289]
I want to make a game with minecraft-like terrain, but with each block being 25% smaller for higher detail (maybe even smaller).  Is this even possible with this module, or will I have to figure out something myself?

**Comment by UAVwaffle** [comment]
Also how do I mark this as a issue or a request if the feature does not exist?

**Comment by Zylann** [comment]
The only way to do this at the moment is to just scale the terrain, or make your character larger.

Also this was already asked in #232 and #105.

**Comment by UAVwaffle** [comment]
Thx,  One final question, how do I increase the radius that voxels are generated/viewable.  I couldn't find anything on that.

**Comment by Zylann** [comment]
To increase view distance, there are two places to look at:
- Terrain node max view distance property
- VoxelViewer view distance
The resulting view distance will be the minimum of the two. You may be able to choose different values depending on what the viewer really is, or if your terrain has fixed bounds (or non-infinite).

I think this issue could be closed because the question has been posted twice already.

**Comment by UAVwaffle** [comment]
Thanks for the help, and this amazing module. :)
