### ISSUE TITLE
VoxelInstanceLibraryItem generator displays nothing when density is 1 on the vertices emit mode

### ISSUE THREAD

**Issue by lonevox** [Zylann/godot_voxel#307]
https://user-images.githubusercontent.com/38600896/132929529-0f77c9e0-0c21-40fe-a0a8-1fa49cbf3cb9.mp4

**Comment by Zylann** [comment]
I see where it happens, but I dont understand why...
![image](https://user-images.githubusercontent.com/1311555/132954005-38f6c135-e69a-489e-8225-7fac45fdc929.png)
`_density` is `1.0`, `MAX_DENSITY` is also `1`, and I checked if `_density>1` to make sure it wasn't a tiny rounding error. It wasnt reached, yet the result of that is 0.
I checked in ideone:
![image](https://user-images.githubusercontent.com/1311555/132954038-08f359a1-e0cd-4409-b77f-0204e943e86b.png)
And it correctly returns the value of `0xffffffff`.

I could clamp this somehow as a fix, but I'm clueless as to why the results differ.

**Comment by Zylann** [comment]
I pushed a fix in 454d8b2c7f4a9d1dd26eefb3f06185e0ad39879e

**Comment by aaronfranke** [comment]
The code succeeds in ideone because it was optimizing away the multiplication. At runtime we would expect `0xffffffff * 1.0f` to cast `0xffffffff` to a 32-bit float to give `0x100000000` which will be `0` when casted to `uint32_t`. We can check that this is the case by forcing the compiler to not optimize away the operation using the `volatile` keyword:

![Screenshot from 2021-09-12 10-33-35](https://user-images.githubusercontent.com/1646875/132994104-de202d75-8a4f-4a38-b26c-4a68d4e0ae5e.png)
