### ISSUE TITLE
Request: Custom rotation for instances in VoxelInstanceGenerator

### ISSUE THREAD

**Issue by lonevox** [Zylann/godot_voxel#308]
![rotation_please](https://user-images.githubusercontent.com/38600896/133011800-7d5546dc-b307-469d-80f7-4a874f1a100b.PNG)
Options for rotation are very limited.

Rotations of instances currently look random as seen in the image above. I'm not sure if this is actually random or is due to the vertex/face the instance is on, so I don't know how possible this is, but it would be nice to have options in VoxelInstanceGenerator for both:

- Disabling X, Y, or Z rotation for all instances individually (so the current "random" rotation isn't applied).
- Add a custom X, Y, or Z rotation offset to all instances, which is added to each individual instance's current rotation (and would still have en effect if the random rotation is disabled).

This gives finer control to the instances.

**Comment by lonevox** [comment]
Come to think of it, it's probably better to have a slider between 0 and 1 for X, Y, and Z that controls how much randomness is applied, rather than disabling the random rotation entirely.

**Comment by Zylann** [comment]
It's random, but it's not working with XYZ euler angles at atll. It can't, because the surface the instances spawn on can be oriented in any direction. So specifying axes will suffer from gimbal lock in some way.
What are you trying to achieve with this?
You could try implementing what you need in here: https://github.com/Zylann/godot_voxel/blob/3ee79ec068129c35393e790d4a8f44416b2ff428/terrain/instancing/voxel_instance_generator.cpp#L380

**Comment by lonevox** [comment]
In my case I just want an option for disabling all random rotation. I managed to get what I want working, however as you said it isn't perfect because of vertical alignment. I made a pull request [here](https://github.com/Zylann/godot_voxel/pull/309). I'm happy to remove it though if this isn't desired.

**Comment by Zylann** [comment]
I added an option to turn off rotation in c18262d3f89ba1518371af41a8f8939f82d1cf0d
