### ISSUE TITLE
Need mesh transform relative to terrain in shader.

### ISSUE THREAD

**Issue by m4nu3lf** [Zylann/godot_voxel#310]
Problem:

In my project, I want to render the terrain (an asteroid) in the mission menu and rotate it with the textures rotating with it.
Right now, this is not possible because the shader only has access to the global mesh transform.
To achieve this the world matrix has to be replaced with the matrix relative to the terrain transform in the shader, but given materials are copied, I can't find a way to pass that piece of information to the shader.

I can try make a PR myself if this feature makes sense for the project. The change will add the possibility to specify a shader uniform recognized by the terrain, which will provide  that matrix for each mesh block. The code will keep it up to date if the block transform changes.

**Comment by Zylann** [comment]
To clarify, do you need this because you use triplanar mapping? And local space would not work because it seems to make the textures repeat at the seams?

Which node are you using?
From what you say about materials being unique per block, I assume you use `VoxelLodTerrain`. In which case, the parameter you are looking for already exists:
```glsl
uniform mat4 u_block_local_transform;
```
Used in this demo: https://github.com/Zylann/solar_system_demo/blob/012f1a674dec01ba4bb9f3a6efc53b5d776e0bf9/solar_system/materials/planet_ground.shader#L11

**Comment by m4nu3lf** [comment]
Yes, that is exactly what I was talking about. I'm closing this issue, thanks!
