### ISSUE TITLE
Module wont compile when "float=64" flag is set

### ISSUE THREAD

**Issue by anatole-dp** [Zylann/godot_voxel#358]
as said above i attempted to compile Godot 4 with the float=64 flag and it created issues . . . attatched is a file that has the console output during compiling if its of any use.

[floatError.txt](https://github.com/Zylann/godot_voxel/files/8056352/floatError.txt)

**Comment by Zylann** [comment]
Double-precision support could be worked on.

Here is a list of things worth noting though:

- FastNoise2 does not support doubles so far. SIMD noise is often 4 times faster, but won't be usable with doubles. And when it gets support for them, it will run at half the speed because a `double` takes twice as much space as a `float` in SIMD registers.

**Comment by Zylann** [comment]
Just pushed a first step for the module to compile with doubles in 48081faf03e5f53081d208bc195c20d613df7636 
It might still not compile, but it addresses a bunch of things regarding that.

**Comment by Zylann** [comment]
It should now compile with `float=64` with 31b4d0bc68d5d0efa37187a70beca2e947117df1
