### ISSUE TITLE
Question with Multiple Voxel Objects

### ISSUE THREAD

**Issue by Denzeduous** [Zylann/godot_voxel#359]
Hello,

Absolutely amazing project you have here. I was just wondering, as I couldn't seem to find it anywhere in the documentation, but is it possible to mix a smooth and blocky voxel world using two different `VoxelViewer`s? I was looking to create something like Space Engineers with multiple grids separate from the main world, and was looking to see if this is possible or feasible (particularly with performance). My original idea was to have multiple "voxel worlds" as I didn't see a way to do voxel objects. These "worlds" would move (and rotate) independently of one another. The thought behind this is it could allow for ships, space stations, and ground stations to all move around as well as interact with one another (is that possible?).

I would love to know if what I am thinking is possible, as it could cut out a CONSIDERABLE amount of work on my end. Mainly, I want to know: Can I have multiple ships, stations, and the planet together by having different worlds that can _collide_ and _interact_ with one another while being rendered separately? And is there any way to have them render as they would if they were normal objects (where, for example, if one ship is underground it's impossible to see as the planet is covering it, or if one ships is colliding with another, the voxels possibly intermingled, they display in the proper rendering order)?

Thank you, and I hope you have an amazing day :)

**Comment by Zylann** [comment]
> is it possible to mix a smooth and blocky voxel world using two different VoxelViewer?

`VoxelViewer` is only a hint for the engine to prioritise updates nearby. They have nothing to do with voxels being smooth or blocky.

> I was looking to create something like Space Engineers with multiple grids separate from the main world

Keep in mind Space Engineers construction is not a "voxel" one in the same sense as this engines does. Just because there is a grid of some sort doesn't mean it has to be handles the same. This engine uses quite specific meshing algorithms, and likely one like Space Engineers requires something a bit more custom.

> My original idea was to have multiple "voxel worlds" as I didn't see a way to do voxel objects. These "worlds" would move (and rotate) independently of one another

What do you actually mean by that? If you mean planets, that is achievable with multiple terrain nodes, you don't need entire worlds for that (see https://github.com/Zylann/solar_system_demo)

> Can I have multiple ships, stations, and the planet together by having different worlds that can collide and interact with one another while being rendered separately?

In theory that is still something you would do with multiple terrain nodes, really. However right now there is no support for rigidbody physics between them, only static. Also I'll say it again, it is very likely IMO that you would need a much more specific system to handle constructs like ships and vehicles with physics and tons of other functions attached to them. This engine is better suited for terrains right now.

**Comment by Denzeduous** [comment]
Hello Zylann,

Thanks for the information! I was hopeful, but unfortunately it seems I'll have to be doing the hard work myself if I decide to go through with the project :stuck_out_tongue:. This was really informational. As for what I meant with "worlds", it was different terrain nodes and was just a hacky idea I had based on what I could gather from the documentation. Have a great day!! Great project you have here so far!
