### ISSUE TITLE
Inheriting VoxelTerrain from gdnative

### ISSUE THREAD

**Issue by BogdanAlexandru** [Zylann/godot_voxel#376]
Hey, sorry if this is mentioned in the docs, I was unable to find anything.

I compiled godot 3.5beta4 with the module and it works great on its own with gdscript, however I'm using gdnative to write some parts of my game in C++. I tried to inherit VoxelTerrain like:

`class TerrainManager : public VoxelTerrain`

the issue comes from the fact that Voxel Tools is a module and all its source files expect headers & co. to be coming from godot's sources whereas my code expects them from the gdnative headers (I followed the steps in getting started with gdnative in C++).

This results in ambiguities and compile errors - however I'm not even sure doing what I'm trying to do is the best idea? Is there a way out other than writing my own game's logic as a module so it sits beside VoxelTools?

Thanks for this library, it looks super awesome.

**Comment by Zylann** [comment]
What problem do you have exactly? You tried to litterally copy the source code of this module into your GDNative project? Indeed that won't work at all. Not only because modules use the API of Godot's core source, but also because the master branch is for Godot 4 and GDNative is Godot 3.

Because this is a module, you need to compile Godot itself with it, and THEN you generate the `api.json` (which will then contain info about voxel classes) so when you compile GodotCpp it will generate wrappers for these classes, which in turn allows you to access and inherit from them in GDNative.

**Comment by BogdanAlexandru** [comment]
> you generate the api.json (which will then contain info about voxel classes) so when you compile GodotCpp it will generate wrappers for these classes, which in turn allows you to access and inherit from them in GDNative

Yup, that's what I was missing. Thanks for the answer, I'll try it soon :+1:
