### ISSUE TITLE
Update terrain live when editing graph generator

### ISSUE THREAD

**Issue by rcorre** [Zylann/godot_voxel#405]
When I'm editing a graph generator in the editor, I often find myself clicking the "Regenerate Terrain" button after every change, to visualize what effect it has.
It would be nice if there were an option to regenerate the terrain automatically after every change.
I have a patch here against the 3.x branch that is working well for me: https://github.com/rcorre/godot_voxel/commit/c4245cda67fab5432e9e3f8a592f3d289dd33b08.
Would such a feature make sense in the project?

It possibly could be made smarter by only updating if the edited node has a path to an output node.

**Comment by MGilleronFJ** [comment]
I think it may be done in such a way any generator works, not just the graph one. Perhaps the `changed` signal could be used. Also, I dont think it should regenerate immediately because it is expensive, it might make the editor stutter often while you change settings, so at least it should be optional.

**Comment by rcorre** [comment]
> I dont think it should regenerate immediately because it is expensive

I'm hooking into the same de-bouncing logic as preview updates (which delays 0.5s before updating): https://github.com/rcorre/godot_voxel/commit/c4245cda67fab5432e9e3f8a592f3d289dd33b08#diff-94d26bfa074a7e9c9bf772d0aa63456860d15dfb58a15e4585c56aeb36826764R299-R301

> at least it should be optional

It is off by default, and enabled by a checkbox next to the "Range Analysis" button: https://github.com/rcorre/godot_voxel/commit/c4245cda67fab5432e9e3f8a592f3d289dd33b08#diff-94d26bfa074a7e9c9bf772d0aa63456860d15dfb58a15e4585c56aeb36826764R192-R195

**Comment by Zylann** [comment]
I can add it to the master branch, but Godot 3.x is supposed to only get bug fixes, or the feature will need to be backported

**Comment by rcorre** [comment]
> I think it may be done in such a way any generator works, not just the graph one

I wouldn't be sure where to put the "enable" button, since I did this in the Graph Editor toolbar. I guess it could be a property on the `Generator` instead?

**Comment by Zylann** [comment]
I actually changed my mind on that. If that is required, it may be implemented such that each generator can provide its own logic, and otherwise others could default to a generic one that listens to `changed`. The reason is that `VoxelGeneratorGraph` has more complex change logic than the others, and a generic system would kinda clash with it.

I started implementing this, just not sure yet about detecting unecessary changes.

**Comment by rcorre** [comment]
Personally I have no strong feelings about whether it works for other generators. I've found it incredibly convenient for the graph generator so far. 

Detecting unnecessary changes would be nice, but not critical. Seeing the graph flicker when I tweak connections that don't have a route to the output yet is barely annoying, and I'm not losing sleep over the wasted CPU :)

**Comment by Zylann** [comment]
Added to master in 8a9825847ede6956e7a25ebeecf5e531747c2b03

**Comment by rcorre** [comment]
Live editing works great in main. Thanks!
