### ISSUE TITLE
Cant delete Graph Nodes in  godot_voxel 3.X using godot 3.5.1

### ISSUE THREAD

**Issue by BleedingXiko** [Zylann/godot_voxel#457]
When clicking on a node then pressing the delete key, the following error comes up 

`
 core\object.cpp:1242 - Error calling method from signal 'delete_nodes_request': 'VoxelGraphEditor::_on_graph_edit_delete_nodes_request': Method expected 0 arguments, but called with 1..
`

**Comment by Zylann** [comment]
There was a compatibility-breaking change in Godot 3.5, an argument was added to `GraphEdit.delete_nodes_request`, so it breaks the module in that version. I'm no longer working on that branch so I havent fixed it so far.

The fix is to add an argument to `_on_graph_edit_delete_nodes_request(Array node_names)`, like in the master branch. I had no use for this argument though.

**Comment by BleedingXiko** [comment]
Okay thanks, do you know what script i would find that function in?

**Comment by Zylann** [comment]
It declared in `editor/graph/voxel_graph_editor.h` and defined in `editor/graph/voxel_graph_editor.cpp`.

**Comment by Zylann** [comment]
Should be fixed by d31c82a585b6f613ec3324cd493e970c544e9c16

**Comment by Zylann** [comment]
Is this still happening?

**Comment by BleedingXiko** [comment]
Its fixed 👍 sorry should have closed the issue awhile ago.
