### ISSUE TITLE
[Bug] Texture atlas showing the wrong texture with blocky terrain type

### ISSUE THREAD

**Issue by Robinerra** [Zylann/godot_voxel#488]
Using the latest build (godot 4.1) on linux.

Here's my spritesheet (Beautiful art, i know):
![spritesheet](https://user-images.githubusercontent.com/104485878/222936071-643da170-9eb7-4acf-90bf-584677461866.png)
Here's the properties for my block
![Screenshot_20230304_170442](https://user-images.githubusercontent.com/104485878/222936079-8e06d28d-5f4f-4f7e-8f42-690fa3355a0f.png)
Here's what shows up in game
![Screenshot_20230304_170514](https://user-images.githubusercontent.com/104485878/222936093-99b61329-19d8-479b-912a-28a6918afc46.png)
![Screenshot_20230304_170758](https://user-images.githubusercontent.com/104485878/222936127-e4784dde-fe4b-4995-80e8-251405b6cab8.png)
(I'm also having various graphics problems too like lines on the edges of blocks)

I'm not sure what I'm doing wrong and i've been stumped for an hour or two. Thank you.

**Comment by Zylann** [comment]
About the tiles:
When you set geometry to `CUBE`, the `atlas_size` property gets used to resolve pixel coordinates of your tiles. It assumes you use a square atlas , by default 16x16 (hence `16`). Your atlas is 1x3, so it won't work. You should resize your atlas to be square (maybe 3x3, and set `atlas_size` to 3, or resize your atlas to be 16x16).

About lines on the edges: this is caused by filtering. If you are looking for a pixelated look, you should change the sampling mode in your material.

**Comment by Robinerra** [comment]
Thank you so much! I was under the impression that atlas_size was the amount of pixels per tile. I changed the atlast to be an 8x8 square and I set the atlas_size to 8 and that worked, all faces display correctly. Changing the filter to nearest fixed the blurriness and lines. There's a new issue now, this weird sub-pixel line on the left of each block.
![Screenshot_20230304_214713](https://user-images.githubusercontent.com/104485878/222943886-35072463-a9ea-43a1-a201-3c1a2a2a9387.png)

**Comment by Robinerra** [comment]
Changing the atlas_size to 8x8 and making my atlas's file to 128x128 worked perfectly (I was under the impression atlas_size was for the size of each title in the atlast, i.e 16x16 pixel tiles), and changing the sampling to nearest fixed the bluriness and the lines. thank you so much!
