### ISSUE TITLE
Any reason for not using "auto" on code base?

### ISSUE THREAD

**Issue by afonsolage** [Zylann/godot_voxel#49]
Hello folks!

I'm just wondering if there is any reason why not use the `auto` keyword of C++? It's been there since C++11 and our code base can compile C++17 if I'm not mistaken.

In some parts of code, instead of typing:
```const VoxelLightSpreader::OutputBlock &out_block = output.blocks[i];```

One would just do:
```auto &out_block = output.blocks[i];```

I'm asking it before using `auto` because we should have some kind of "code convention" IHMO.

Thanks!

**Comment by Zylann** [comment]
So far I've been following similar conventions to those of Godot itself, but since I openly use C++11 features here it's a bit more relaxed. I'm not a fan of `auto`, especially when the type cannot be deduced by solely looking at the line. So I would suggest to not use it, unless it's a horrible one like STL iterators. In other situations I preferred `typedef` (Like `Mgr` in updater and streamer).

**Comment by afonsolage** [comment]
Got it. To be honest, I don't see a problem when using `auto`, since whenever we are developing C++ we use a IDE, which quick shows us the variable type and, in most cases, you don't really care for the type, since generally you receive it from a function or struct/class members whose the type was already declared someplace else.

When declaring I may agree, since `auto i = 0` may sound ambiguous between `int` and `unsigned int`.

But anyway, I'll keep not using `auto` keyword, since most time of my development should be on GDScript, so this shound'nt be a problem.

Thanks!
