### ISSUE TITLE
finding height in VoxelGeneratorGraph

### ISSUE THREAD

**Issue by localwhale20** [Zylann/godot_voxel#530]
i'm trying to implement simple generation, for ex. if height is 64 then place white block and if height less than 64 then place black block.
i don't know how to find the height
maybe i'm stupid for this generators /shrug

**Comment by Zylann** [comment]
VoxelGeneratorGraph does not generate height specifically. It generates values from a 3D positions. Wether these values are heights or something else is up to you. It's like having a 3D for loop and it's up to you to fill what goes inside.

To do what you describe, there will to be a problem, because if "place white above 64, black below 64" is all there is, then your world will be entirely filled with matter and there won't be any air. Which in terms of 3D meshes, means you won't see anything, as there is no surface anywhere (no transition from "matter" to "air").

If you think about height, I guess part of your generator has to produce a heightmap?
And what kind of terrain do you want? Is it smooth or blocky?
You may have to explain more what you actually want to do here^^"

**Comment by localwhale20** [comment]
i was implementing generator using script, but this was hard and i want to implement it using graph. i forgot to mention air, this was just for example, so i can understand basics of this.

**Comment by Zylann** [comment]
Graph is semantically similar to a script, just laid out differently and running faster with different constraints. You still need an understanding on what the calculated values represent.

Height is not something that a graph gives you. It's something you decide.

If you want to make terrain based on 2D noise heightmap, then you would make a graph that looks like this:
https://voxel-tools.readthedocs.io/en/latest/generators/#usage-with-blocky-voxels

What that graph does is to compute 2D noise from X and Z and multiply it, which can serve as a height. Then the graph compares that height with the Y coordinate and decides wether to place air or matter using a Select node.

**Comment by localwhale20** [comment]
i'll try to mess around graph, maybe i'll understand something better

**Comment by localwhale20** [comment]
i'm again getting `modules\voxel\meshers\blocky\voxel_blocky_model.cpp:302 - Not implemented` errors when trying to regenerate terrain. library consists of: 0 - VoxelBlockyModelEmpty, 1 - white VoxelBlockyModelCube

**Comment by Zylann** [comment]
You can ignore that error, it's a bug, but should not cause issues for now

**Comment by localwhale20** [comment]
it don't generate terrain in editor mode

**Comment by Zylann** [comment]
If it doesn't then your generator likely isnt generating anything.

**Comment by localwhale20** [comment]
nvm, reloading project fixes this

**Comment by localwhale20** [comment]
can i contact you from discord, so i won't fill this issue with trash?

**Comment by Zylann** [comment]
There is a Discord: https://discord.gg/pkXmESmrAR
