### ISSUE TITLE
VoxelGenerator will receive extra calls to generate partial blocks outside the bounds of VoxelTerrain

### ISSUE THREAD

**Issue by bgie** [Zylann/godot_voxel#543]
**Describe the bug**
VoxelGenerator will receive extra calls to generate partial blocks outside the bounds of VoxelTerrain.

**To Reproduce**
Create a VoxelTerrain and set the bounds to (0,0,0) -> (16,16,16), keep the mesh_block_size at 16
Add a VoxelGeneratorScript and in the _generate_block function add code to print buffer.get_size() and origin_in_voxels.

**Expected behavior**
I would expect the generator to be called only ONCE for the block at (0,0,0), requesting a block of size 16x16x16.

Yet there are 6 extra calls, with 1 thick slices of a block, making up an extra border of 1 voxel around the central block.
Either this is a off-by-one bug, or is it by design?

For my project, I want a shallow world of only 16 or 32 Y in height. (Digging too deep is very dangerous, ask any dwarf).
Having only 1 block for a certain XZ position makes instancing my units way easier, the height is not split up into blocks.

** Workaround **
If you want a shallow world like me, simply ignoring the extra blocks is an option. This does force you to make assumptions about the contents of those blocks.
Still, if this is not by design, it seems like a waste of compute, so might as well report this.

**Comment by Zylann** [comment]
> Yet there are 6 extra calls, with 1 thick slices of a block, making up an extra border of 1 voxel around the central block

This is by design, at least for `VoxelLodTerrain` where only edited blocks are stored by default, but the logic being re-used it's possible that it ended up doing that too for `VoxelTerrain`?

The idea is that to build the mesh of a block, neighbor voxels are necessary. in a 16-voxel mesh size scenario, the task doing this requests 27 blocks centered around the current block coordinate, and makes a temporary copy of voxels including neighbors to be passed to the mesher.
However, if some neighbor blocks cannot be found, the task will assume they were not edited or saved, therefore it generates them on the fly. And since it is wasteful to generate entire blocks, it asks to generate only the needed voxels.
This might not matter for some generator designs, and is actually important in a setup where only edited blocks are stored in memory. But it becomes a problem as soon as you make assumptions about the area passed to `generate_block`.

The fact this logic comes up with all 6 sides in VoxelTerrain is a bit puzzling though, not sure how that happens. My first guess would be that the task is unaware of the finite world border, so bordering chunks might falling back on that logic. But to get that on all 6 sides, there would have to be only 1 block in the entire terrain, which is surprising.
The blocky game demo project uses `VoxelTerrain` with a custom generator, and doesn't seem to be bothered by this (if it happens at all?).
Needs some investigation to figure out if we can bypass this behavior in certain setups.

**Comment by bgie** [comment]
I guess I was assuming things to be simpler than they are... so not an off-by-one bug but related to meshing. Thank you for the quick response.

I _am_ generating a world with 1 single block so if you need the 1 voxel padding around the entire world, the 6 extra blocks are to be expected.

The extra blocks being generated are not drawn anyway, I manually counted my 16x16x16 block and it is of correct size. So my problem is solved now I know these extra blocks are only relevant for rendering, I can safely ignore them as 'out of bounds' for my unit instancing.
