### ISSUE TITLE
how to get past versions? 

### ISSUE THREAD

**Issue by Xinoviea** [Zylann/godot_voxel#593]
I'm trying to get godot_voxel for version 3.5.3 of godot. but can't seem to find it anywhere. so where can I find a past version of this that works with 3.5.3 of godot? thanks in advance!

**Comment by Zylann** [comment]
The only prebuilt binaries you can get on Github are either the Releases (which I only started recently), and "nightlies" with Github Actions artifacts, but they expire after some time. Development has shifted to Godot 4 now, so you won't find such builds for Godot 3. I also don't work on that version of Godot anymore.

There is a Godot 3.2.2rc build still available on [Tokisan Games](https://tokisan.com/godot-binaries/#downloads), but as you might guess, it's very old now, it was from march 2020.

If you really need something that might build in Godot 3.5.3, you can try to build Godot 3.5.3 yourself with the [godot3.x](https://github.com/Zylann/godot_voxel/tree/godot3.x) branch of the module. You might have to fix some compiling stuff too, if Godot broke some API compatibility. However you won't have any of the features and improvements of the module that happened since.

**Comment by Xinoviea** [comment]
thank you so much for responding, and that sucks, I honestly have no clue on how to build them myself, as overall it seems complex, and from what I've seen, you need to install tools to compile them, so to ask, is there any easy way to compile this with godot? or at least a guide to? but thanks again for responding, I hope one day we could get some releases of past versions of this on older godot, even if they aren't being updated as some projects use past versions of this voxel engine. but thanks again for responding, it does mean a lot and keep up the great work!

**Comment by Zylann** [comment]
To install a module, you need to download the source code of Godot, copy the module's repo inside the `modules/` folder of Godot, and rename its folder "voxel".
Then to compile Godot 3.x, follow instructions from the docs: https://docs.godotengine.org/en/3.5/development/compiling/index.html

**Comment by Xinoviea** [comment]
Thank you so much, this helps a lot. and I'm sorry for the late response, I was asleep, and for whatever reason, I don't get notifications from this post despite being subscribed to it. anyway, thank you again, I hope you have a great day and keep up the great work!
