### ISSUE TITLE
[LOD Terrain] Image node with large EXR causes missing chunks.

### ISSUE THREAD

**Issue by Illauriel** [Zylann/godot_voxel#613]
**Describe the bug**
Using Image voxel graph node with a 4K exr image converted from a RAW downloaded from Unity terrain produces missing tiles at LOD 0 if connected to an SDFPlane and multiplied by something >32. 
![Screenshot 2024-03-30 030033](https://github.com/Zylann/godot_voxel/assets/10573379/5e247702-1b7e-479c-bf4d-9231c04adb82)

**To Reproduce**
1. Create new LOD terrain, add VoxelGeneratorGraph 
2. Connect nodes like this
3. Observe holes form around VoxelViewer

**Expected behavior**
Graph correctly interprets image as input heightmap

**Environment**
- OS: Win11
- Graphics card NVIDIA GeForce RTX 3060 Laptop GPU
- Godot version v4.3.dev.custom_build [29b3d9e9e] (Mar 30)
- Module version [d07a94d]
- Renderer used Forward+

**MRP**
[zero-exr-mrp.zip](https://github.com/Zylann/godot_voxel/files/14809764/zero-exr-mrp.zip)

**Comment by Zylann** [comment]
Looks like something is wrong with range analysis. It doesnt report expected values. If you set SDF Clip Threshold to 9999 the problem seems to go away, though it affects performance.

**Comment by Zylann** [comment]
I fixed a bug with wrapping coordinates in 020cb0bab84f2f4404a422edf3f77b18dd1d1340, which seems to fix your particular MRP, however you'll have to change Subtract nodes to 1024 instead of 2048, because the fix removes an incorrect offset of the image in negative coordinates, which your nodes triggered.

There is still a bug with range analysis though, which starts to occur if you attempt to evaluate an image beyond one repetition. Your current MRP triggers that too, but not if you "fix" Subtract nodes to 1024.

**Comment by Zylann** [comment]
The other bug should be fixed by 682783dd53b67bcfd1b961a0ce4e8919d4ce3148
