### ISSUE TITLE
Smooth Planet generation with cubic voxels?

### ISSUE THREAD

**Issue by Shadowblitz16** [Zylann/godot_voxel#614]
https://www.youtube.com/watch?v=bJr4QlDxEME

Please watch the whole video.
The solution he uses to fix the distortion could be linear interloped so the change from voxels to sphere mesh are gradually changed as your going towards the planet.

**Comment by Zylann** [comment]
I have seen all that already. I still have no plan to implement it.

**Comment by Shadowblitz16** [comment]
> I have seen all that already. I still have no plan to implement it.

Is there a reason why?

This is a voxel module and it fits within the definitions of what a voxel module would do.
So far, at least to my understanding is this module is very minecraft game specific.

**Comment by Zylann** [comment]
> Is there a reason why?

I'm just not interested by that kind of technique. I don't have to do this work to add X to the module just because X uses voxels. While it could fit in a voxel module, it's still a lot of work as it affects every algorithm and data structure involved, a whole new terrain class pretty much. SeedOfAndromeda had a dedicated system for the game they were making.
