### ISSUE TITLE
Skirts between differing LOD borders occasionally leave holes

### ISSUE THREAD

**Issue by tinmanjuggernaut** [Zylann/godot_voxel#63]
![image](https://user-images.githubusercontent.com/632766/64362574-b9359f80-d049-11e9-87b3-aa95a36e9dcd.png)

![chunk loading](https://user-images.githubusercontent.com/632766/64231418-8c3e9b00-cf2a-11e9-91ba-e330f7712e4e.gif)

See more in action with different materials: 
https://youtu.be/uNVG_49DGNo

@Zylann said: 
> These are supposed to be hidden by skirts most of the time, but they can still show up. Either because skirts are too short (but couldnt figure out a better sweetspot), or because adjacent octrees have slightly different outcomes in their subdivisions which makes them not line up as if they were one.

In #59 this was identified as an issue with marching square skirts.

This is different from #57 which appears to be rendering in between the removal and repairing of the terrain during edits.

**Comment by tinmanjuggernaut** [comment]
Nick Gildea [referenced in #24](https://github.com/Zylann/godot_voxel/issues/24#issuecomment-528491799) posted two blogs about stitching seams between chunks on his Dual Contouring terrain. 

He says at the end of the first if you're using marching cubes you'll need something like Transvoxel. But since you use Octrees with DMC, maybe it's useful?

https://ngildea.blogspot.com/2014/09/dual-contouring-chunked-terrain.html

https://ngildea.blogspot.com/2015/07/fixing-seams-bug.html

**Comment by Zylann** [comment]
There is a huge caveat coming from Godot when it comes to handling seams: they either have to be part of the mesh, or be separate meshes.

In the first case, this requires to remesh A LOT more times than necessary, since any edit or LOD transition requires to rebuild and re-upload the entire mesh and its neighbors on each update.

In the second case, this basically triples the amount of meshes Godot has to render, so triples draw calls and slows down culling.

Last time I investigated this, seams could be swapped in and out by directly altering the rendering method (index buffers?), which ideally doesn't involve any remesh or reupload since seam configurations would already be embedded in the mesh. Other "correct" methods also involve altering the rendering itself, which is not possible without forking VisualServer to add specific methods. No wonder voxel engines are often best built in completely custom engines^^"
This is why I've been settling on simpler methods like marching squares, or another one I have in mind which is to over-polygonize a little bit using a slightly higher isolevel.
There might be techniques involving shaders, but doing this may constrain the way to write shaders for this kind of terrain.

Note: I'm not really using octrees for mesh generation. There is one in DMC but it's not as effective as I thought.

**Comment by Zylann** [comment]
Update: it would seem VoxelFarm does create extra meshes for the seams in Unity, which is probably ok in this context since Unity can do dynamic batching as the material remains the same.
My hopes are quite low regarding the performance impact of this method in Godot but I'm not opposed for someone to try it.

Also:
![image](https://user-images.githubusercontent.com/1311555/64446916-fb0a2880-d0d1-11e9-8888-571a3d27c70e.png)
I need to add viewer pinning to the demo so we can see what this geometry actually looks like, that hole "doesn't look right".

**Comment by tinmanjuggernaut** [comment]
Most (all?) holes appear on LOD borders.

In the top row, the hole appears only when LODs 3 and 2 are next to each other. When it's all L3 (4th pic) or all L2 (5th pic) they don't appear. I moved the camera back and forth and counted LOD shifts from 0.

In row 2, notice the overdraw does not show a hole for the top one.  

In rows 2 & 3, the size of the meshes looks like where L3 and L2 connect, as above. 

In row 4, this particularly large hole appears where L3 and L4 connect.

The visual scale is about the same for all pics. The landscape is farther and looks like it in the last row.


![image](https://user-images.githubusercontent.com/632766/64888397-dc91c780-d6a5-11e9-8bc5-3b1f3e827fb3.png)

**Comment by Zylann** [comment]
I just found out `VoxelStreamNoise` is busted when it comes to LOD. The noise buffer optimization has a bug in it, which causes LOD data to not exactly line up with differing lods. With marching square skirts this was kinda rare to see but holes could occasionally be found. With Transvoxel it's now obvious because seams of that algorithm are supposed to be perfectly lined up, assuming blocks of different LOD share half of their values thanks to nearest-neighbor downscaling.

Screenshots posted earlier show `VoxelStreamImage`, it's possible it has the same problem but I haven't done the same test on it yet.

**Comment by tinmanjuggernaut** [comment]
This one here https://github.com/Zylann/godot_voxel/issues/63#issuecomment-531359438 is `VoxelStreamNoise`.

**Comment by tinmanjuggernaut** [comment]
Transvoxel has fixed the holes in the mesh in this ticket. However, it has introduced a different type of hole as the highest LOD is disconnected from the rest.

![image](https://user-images.githubusercontent.com/632766/71762434-0cd9cc00-2f0a-11ea-8036-9caa894f4db3.png)

**Comment by Zylann** [comment]
I can't see them:
![image](https://user-images.githubusercontent.com/1311555/71847375-a220c000-30c4-11ea-8acf-05185cf2100d.png)

**Comment by tinmanjuggernaut** [comment]
I saw it on VLT heightmap using distance 4096, LODs 8.

**Comment by Zylann** [comment]
Indeed. Close-up, we can see a working transition mesh on one side, and the other side totally missing one. The neigbor has a transition mask of `0`, which is invalid.
![image](https://user-images.githubusercontent.com/1311555/71850674-bff22300-30cc-11ea-8e8a-b57f0cd50895.png)

**Comment by Zylann** [comment]
I think I fixed it with 051034fc519b191f07bc3b95451d973e236eea5e

**Comment by tinmanjuggernaut** [comment]
Yep, even extending out the terrain beyond the far clip I see no holes anywhere. Good job!
