### ISSUE TITLE
Unused model IDs leftover in BlockyTypeLIbrary

### ISSUE THREAD

**Issue by ArchLinus** [Zylann/godot_voxel#630]
**Describe the bug**

Deleting a `VoxelBlockyType` will leave behind unused model IDs.

These model IDs are junk and can cause gameplay issues for systems which which expect certain type IDs. For example, `VoxelAStarGrid3D` seems to rely on empty space being model ID 0.

**To Reproduce**
1. Assign a VoxelBlockyTypeLibrary to a VoxelMesherBlocky
2. Add a VoxelBlockyType
3. Save the scene
4. Delete the VoxelBlockyType
5. Save the scene again
6. Click "Inspect IDs" and observe that there are unused model IDs.

**Expected behavior**
Removing a type should reset the model IDs to how they were before the type was added.

**Screenshots**
![image](https://github.com/Zylann/godot_voxel/assets/126534522/e2b022d2-6ccd-4180-9711-7584f182d33c)

**Environment**

Godot v4.3.dev.mono (6118592c6) - Windows 10.0.22000 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.5123) - 12th Gen Intel(R) Core(TM) i5-12600K (16 Threads)

- Module version 68d129c1dd7c3dcda323a0ccd2fbe52c7cae1b79

**Comment by ArchLinus** [comment]
I understand now that the model IDs are intended to remain the same after changes. I assume the reason for this is so that serialized voxels will remain consistent even when the type library is changed?

Perhaps a button could be added to recompute the model IDs, and warn that existing saved voxels will be invalid? 

Or maybe the ID map can be saved into the voxel data itself? I'm not familiar with how the voxel serialization works so I don't know how practical that would be to do.

**Comment by Zylann** [comment]
> Deleting a VoxelBlockyType will leave behind unused model IDs.

In the current state of the system, this is intented. When you add, change or remove models, you have to keep in mind existing saves.

> can cause gameplay issues for systems which which expect certain type IDs.

In this system, you are not supposed to deal with IDs directly, and you should not expect a certain model to always have a certain ID. Every game version, or even each world could have different IDs. Inspecting them is only a debugging tool.
I think maybe an ID will be re-used only if you re-create models that end up having the exact same name and attributes.

> VoxelAStarGrid3D seems to rely on empty space being model ID 0.

That's a problem with `VoxelAStarGrid3D` (which is itself experimental).

> Perhaps a button could be added to recompute the model IDs, and warn that existing saved voxels will be invalid?

Perhaps yes, though it really is quite a dangerous option if you have existing saves using the system in its current state, because once you clear this there is no way to tell what was what.

> Or maybe the ID map can be saved into the voxel data itself?

That was part of the plan, but at the moment this is not the case so for now the current behavior is what happens. I'm not actually decided how that will happen. An option is that you would do this somehow. The types system is very experimental but I'm not working on this at the moment so it's a bit in a limbo state.

**Comment by ArchLinus** [comment]
> In this system, you are not supposed to deal with IDs directly, and you should not expect a certain model to always have a certain ID. Every game version, or even each world could have different IDs. Inspecting them is only a debugging tool.

This makes sense. Though I do think it would be useful to be able to force a model ID for certain situations. Having air on 0 is a very standard and it would be nice to force the system to always give that ID to a particular block. I can also picture it being useful for debugging purposes, as in code I can just write in a particular voxel value and know it will go to a predefined debug block, or something along those lines. Though not sure how attributes would be factored in.

> Perhaps yes, though it really is quite a dangerous option if you have existing saves using the system in its current state, because once you clear this there is no way to tell what was what.

I did end up creating a button for my own purposes as a stop-gap measure. If you wish, I can clean up the code and submit a PR.

**Comment by ArchLinus** [comment]
Yeah fair enough, I think I will switch to the other library type given the experimental nature of type libraries at the moment. Thanks!
