### ISSUE TITLE
VoxelTool.do_* functions do not ignore VoxelModifier on terrain

### ISSUE THREAD

**Issue by Piratux** [Zylann/godot_voxel#665]
**Describe the bug**
When trying to edit terrain with VoxelTool, the result depends on whether there was VoxelModifier in the area of edit. Effects of this can be noticed when stamping a shape with higher SDF scale.

To show an example:
- on left side, sphere was stamped with `stamp_sdf` with VoxelModifierMesh being there.
- on right side, sphere was stamped with `stamp_sdf` without VoxelModifierMesh being there.
See image:
![image](https://github.com/Zylann/godot_voxel/assets/58703216/567f36f3-becb-4541-801d-ed0bbced664f)

**To Reproduce**
1. Just open up MRP, run the game and press space on keyboard (If this won't work I'll write more precise steps).

**Expected behavior**
SDF values after an edit should be the same with or without VoxelModifier nodes in the edited area.

**Environment**
- OS: Windows 10
- Graphics card: GTX 650 Ti
- Godot version: 4.2.2 stable
- Module version: 1.2.0
- Renderer: Forward+

**MRP**
[Test VoxelMeshSDF stamp with VoxelModifierMesh.zip](https://github.com/user-attachments/files/15846628/Test.VoxelMeshSDF.stamp.with.VoxelModifierMesh.zip)

**Comment by Zylann** [comment]
I think you're using the wrong SDF scale for your stamped SDF, and that's affecting the result. It's a unit sphere you scaled by 30, but you scaled its distance field by 500, which is too much. If you use the same scale 30, the issue is much less (if at all) noticeable:

![image](https://github.com/Zylann/godot_voxel/assets/1311555/0c469dda-ac8d-46d9-a7cd-a891952ac339)

Now I'm less sure about why the presence of a modifier affects it, but that might have to do with differences in gradient.

**Comment by Piratux** [comment]
Yes, I'm aware that I'm using different scales (there are reasons why I'm doing this, but it's a bit out of scope for this issue) and why the issue happens.
Roughly speaking
With sdf scale = 1 values are:
A = [.., -2, -1, 0, 1, 2, ..]

With sdf scale = 1 values are:
B = [.., -20, -10, 0, 10, 20, ..]

Thus,
SDF_UNION(A, B) = MIN(A, B) = [.., -20, -10, 0, 1, 2, ..]
Which causes unwanted blocky look.

My main point with this report, is that, presence of modifier should not affect the result (after all, it's intended to be non-destructive preview of the mesh).

**Comment by Zylann** [comment]
Unfortunately this cannot be "fixed", the problem is you're expecting that using wrong SDF alongside correct SDF to behave correctly, which can't happen.

`stamp_sdf` is a destructive operation, and you're using `Add`, so what was there earlier will affect the result. Modifiers act like "local generator extensions", therefore they are only applied in non-edited areas, before edits. Once the area becomes edited, they are frozen on it, with your destructive edit being done on top.

**Comment by Piratux** [comment]
I should have mentioned in an initial issue, that I expected the sphere on the left to be smooth again, after moving VoxelModifier away as I thought it was applied last.

However, now knowing that modifiers are to be treated as part of terrain this behavior is to be expected.

So this is not an issue.
