### ISSUE TITLE
Double custom_build [15073afe3] crash when installing SQLite GDExtension

### ISSUE THREAD

**Issue by Eerrikki** [Zylann/godot_voxel#668]
**Describe the bug**
When i download 2shady4u's SQLite GDExtension, the [godot.windows.editor.double.x86_64.exe.zip](https://github.com/Zylann/godot_voxel/releases/download/v1.2.0/godot.windows.editor.double.x86_64.exe.zip) crash. If i try to reopen, it crash. If i download it with [godot.windows.editor.x86_64.exe.zip](https://github.com/Zylann/godot_voxel/releases/download/v1.2.0/godot.windows.editor.x86_64.exe.zip), it works, so the issue is only with the double build.

**To Reproduce**
1. run godot.windows.editor.double.x86_64.exe
2. Make a new project
3. Download SQLite (2shady4u) from the AssetLib and install
4. The editor crash and cannot be reopened

**Expected behavior**
I would expect it to work just as it does in the single precision build

**Environment**
- OS: Windows 11
- Graphics card Nvidia RTX 4070
- Godot version Godot 4.2.2.stable.custom_build [15073afe3] + Voxel Tools 1.2.0 (double)

**Comment by Zylann** [comment]
Similar to https://github.com/Zylann/godot_voxel/issues/637

In general, if you have issues adding extensions it's very likely not because of the voxel module. It's either because of Godot's extension system itself, or the version of the extension you're trying to use.

In the present case, I would suspect this is because the extension you're trying to use was not compiled to use double-precision. It really sucks that Godot crashes at you when doing that, but there is nothing I can do unfortunately. You may have to try a build of the extension using doubles.
