### ISSUE TITLE
having constant linear and angular velocity variables like static bodies

### ISSUE THREAD

**Issue by DeepCanionStudio** [Zylann/godot_voxel#669]
im trying to make planets that can move around and rotate
but if a rigid / character body stands on a rotating / moving voxel terrain it behaves like if it was still

in static bodies this is fixed with the "constant linear velocity" and "constant angular velocity" variables that don't move the body but tell other colliding bodies how the body is moving / rotatiting and i think these variables should be added to VoxelLodTerrain and VoxelTerrain

the alternatives are either calculating the movement of colliding bodies from the rotation of the planet or keeping the planet closest to the player still and moving everything else, for now im trying to implement the first option but it would be really useful if those variables from the static body were added to the voxel terrain nodes.

**Comment by Zylann** [comment]
Voxel terrains cannot be used as rigidbodies, and currently there is no plan to make them so. Also terrains are concave colliders, which are not supported by any rigidbody physics in Godot. As you might have found, you can still move them, but don't expect physics on their surface to work correctly.

The [solar system](https://github.com/Zylann/solar_system_demo) demo has moving planets and it solves the issue by changing reference frame when getting close to a planet, which is a signal sent across the game, making the current planet static, and the rest is updated relative to that planet.

I'm not sure if those surface velocities will solve this more elegantly, as moving an entire planet constantly every frame still has a cost, which is even higher if that planet turns out to be the most detailed one due to LOD being close to it. And you still need many other systems to account for that constant motion.
Note that a voxel terrain has no single rigidbody, but *many*, one per chunk, at multiple LODs. So if such properties are exposed they have to update hundreds of rigidbodies every frame.

**Comment by DeepCanionStudio** [comment]
i was able to implement a system similar to the solar system demo pretty easily so yea, at least for what im doing there is no need for these variables

**Comment by DeepCanionStudio** [comment]
i was able to implement a system similar to the solar system demo pretty easily so yea, at least for what im doing there is no need for these variables
