### ISSUE TITLE
How should I properly use the OBJ model exported from Blender?

### ISSUE THREAD

**Issue by qrf0220** [Zylann/godot_voxel#674]
Hello!

When I use an .obj model with UV mapping exported from Blender, if I instantiate an .obj model with UV mapping as a MeshInstance3D directly in the scene, the UV map renders correctly.

However, when I import this .obj model into VoxelTerrain -> VoxelNode -> Mesher (VoxelMesherBlocky) -> voxelBlockyLibrary -> VoxelBlockyModeMesh, the UV map does not render correctly (it appears normal in the preview), but during gameplay, the model appears white.

If I manually specify a material in VoxelTerrain -> VoxelNode -> Mesher (VoxelMesherBlocky) -> voxelBlockyLibrary -> VoxelBlockyModeMesh -> Material Overrides, then the manually specified material displays correctly during gameplay.

Is there a way to directly use the UV map included in the .obj model (by specifying it at VoxelTerrain -> VoxelNode -> Mesher (VoxelMesherBlocky) -> voxelBlockyLibrary -> VoxelBlockyModeMesh -> Mesh -> Surface 0 -> Material)?

**Comment by MGilleronFJ** [comment]
A UV map does not render anything by itself, materials do.
But no, the system does not currently use materials that are already assigned to the mesh itself, it uses what's assigned in the model resource of the blocky library.

**Comment by NuclearPhoenixx** [comment]
The normal workflow would be to use a single material with a texture atlas to be used on as many voxels as possible. This reduces draw calls to the GPU because multiple voxel will be essentially using the same material/graphics.

You might be able to export a material in blender with the obj and then use that. However, for performance reasons it's much better to use the texture atlas approach with a custom material for multiple voxels.

**Comment by Zylann** [comment]
Should be fixed in a3d91655e37bd247db043057585d872da4c91ccb
Though another thing to keep in mind, materials are limited to 2 per model.

**Comment by Anyeos** [comment]
I use gltf that works better with Godot and supports the standard Blender shader nodes.
