### ISSUE TITLE
how prevent rigidbody3d dont go through terrain and stop on top of it

### ISSUE THREAD

**Issue by se8820726** [Zylann/godot_voxel#676]
When applicable, please describe your setup:
- Terrain type: voxelLodTerrain
- Mesher:
- Generator:
- Stream:
- Scene structure:
- Plugin version (or where you got it):  https://github.com/Zylann/godot_voxel/releases/tag/v1.2.0  windows editor double
- Godot version: 4.2.2
- OS: windows
- ...

i used Voxel game demos:
https://github.com/Zylann/voxelgame/project/smooth_terrain/main.tcsn

then i made a rigidbody3d and a child collisionshape3d with default settings
and when i played the scene the rigidbody went through the generated terrain and didnt stop on top of it. why ?

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/2c24078f-1417-460f-8557-fda757447862">

**Comment by MGilleronFJ** [comment]
This is a known "issue" with this module due to how it is designed.

Assuming you turned on collisions, this can happen because unlike regular Godot nodes, terrains in that module use dynamic streaming systems. When the Godot scene starts (after freezing the game until every node is added to the tree), terrain won't be ready immediately. Instead, it progressively loads chunks around the player, and keeps doing so as they move, without blocking the game. So your rigidbody will fall through it if you let it run immediately before chunks around it have reached a high-enough LOD level to have collision.

There are several ways to deal with that:

- Use a raycast down to find when ground starts becoming available
- Check if a small area around your player is loaded or meshed using `VoxelTool.is_area_editable()` (though that might not )
- Check if loading tasks are still ongoing by checking `VoxelEngine.get_stats()`

You can have an animated loading screen in the meantime, pause the game (except the terrain which needs to keep processing) or prevent the player from simulating until either of those conditions are fulfilled.

**Comment by se8820726** [comment]
Both solutions you provided:

`collision_lod_count`
attach `VoxelViewer ` to box
worked, and my problem is solved. Thank you.

However, the current issue is that, for example, I have a very large box, and I attach a `VoxelViewer` to it. Now, using the `view distance` property, I need to set the value so that the entire box fits within the `view distance`, which is quite difficult. It would be better to have a `gizmo` for the view distance value so that I can easily understand which area of the box falls within the `view distance`. 

Thank you.

**Comment by Zylann** [comment]
If you have a physical moving box that is larger than the view distance of a VoxelViewer, you might have quite big problems ahead in terms of simulation stability and performance...

There is no gizmo for viewers distance, but when you use Clipbox the terrain has a debug drawing property `debug_draw_viewer_clipboxes` that draws their chunk bounding volumes.
