### ISSUE TITLE
Need Custom Materials for Any Build

### ISSUE THREAD

**Issue by KingGD24** [Zylann/godot_voxel#679]
I am creating a survival game where you can destroy and place blocks, but with smooth voxels.

[Here is a video](https://www.youtube.com/watch?v=MazA1SlpwTY) that shows smooth voxel terrain with destruction features. However, I want to be able to place blocks of different materials, like grass or stone (smooth voxels). It can be done with the do_sphere function, but it's not possible to make it of different materials. Its not possible to create that is shown in the video.

**Comment by Zylann** [comment]
The way it works in this module is not like this video. It is based on having 4 blending factors per voxel which can blend progressively.

> It can be done with the do_sphere function, but it's not possible to make it of different materials

Have you actually tried it? There is a [demo](https://github.com/Zylann/voxelgame/tree/master/project/smooth_materials) showing that you can have different materials. Just don't expect to use actual *material resources*, because that's simply not the way it works with terrains in general.
Rendering this uses custom shaders and you can actually change that shader to render whatever texture you like. So you can actually get such result. Just through different means.

I guess what the video shows is cool, but "just adding" that without destroying what's in place is work that I currently have no time for at the moment.

**Comment by KingGD24** [comment]
Thanks for telling me, I will try the demo

**Comment by KingGD24** [comment]
Its works thanks and sorry for pulling this.
