### ISSUE TITLE
VoxelInstanceLibrary cannot delete item (cannot determine selected item from property path: 'library')

### ISSUE THREAD

**Issue by Anyeos** [Zylann/godot_voxel#681]
**Describe the bug**
When I click on the recicle bin icon on the VoxelInstanceLibrary it shows an alert that cannot determine selected item from property path: 'library'.
You must select the 'item_X' property label of the item you want to remove.

But it is selected.

I can save it as tres file and next I can open it but similar behaviour: It just ask to delete the selected item but when I press OK it does nothing and print an error message in console:
`voxel/terrain/instancing/voxel_instance_library.cpp:54 - Assertion failed: "p_id < 0 || p_id >= MAX_ID" is false.`

**To Reproduce**
1) Add an VoxelInstancer.
2) create a new library from it.
3) Add any number of items.
4) Try to remove an item.

**Expected behavior**
Of course I expect the selected item to be removed.

**Screenshots**
![Captura de pantalla de 2024-08-10 15-25-45](https://github.com/user-attachments/assets/c32f225b-53c7-4783-a941-eaf32ad08b00)

**Environment**
- OS: Ubuntu 20.04
- Vulkan API 1.3.236 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3070 Ti
- Godot 4.2.2-stable
- 9f99aa0fa8467e420f39643b29f4b334c12f39c9
- Forward+

**Comment by Zylann** [comment]
This is unfortunately an old issue with sub-inspectors. I reported it years ago here: https://github.com/godotengine/godot/issues/54467 but to this day it still hasn't been solved.

While you did select a property in the library sub-inspector, `library` is litterally the property name that Godot is sending to our plugin. Which means it's not possible to figure out which item is actually selected because Godot isn't giving us the full path.

This is where it happens: https://github.com/Zylann/godot_voxel/blob/9f99aa0fa8467e420f39643b29f4b334c12f39c9/editor/instance_library/voxel_instance_library_editor_plugin.cpp#L134

Currently a workaround is to right-click the library and click "Edit" so it takes up the whole inspector instead of being a sub-inspector.

**Comment by Zylann** [comment]
The second error should be fixed in a78c32e57aa5a079886a4bbcde1cd02440a688a6

**Comment by Zylann** [comment]
I pushed a change to the way items are exposed in the inspector. It is now using a Blender-style list where the selected item is shown below. That workarounds the shortcomings of the previous method.
