### ISSUE TITLE
Three sides of voxelTerrain are not getting holes

### ISSUE THREAD

**Issue by se8820726** [Zylann/godot_voxel#684]
When applicable, please describe your setup:
- Terrain type: voxelTerrain
- Mesher: voxelMesherTransvoxel
- Generator: voxel_generator_noise_2d_smooth.tres
- Stream: voxelStreamRegionFiles
- Scene structure
- Plugin version (or where you got it) : double v1.3.0 from here https://github.com/Zylann/godot_voxel/releases/tag/v1.3.0
- Godot version: 4.3
- OS: windows 11
- ...

I have a voxelTerrain node, and three sides of this terrain are not getting holes.

https://github.com/user-attachments/assets/525f9698-5aae-4b33-8556-baddd44fd88d

scene structure:
<img width="1275" alt="image" src="https://github.com/user-attachments/assets/742e9e57-f31b-4116-8650-1f6cd794781c">

**Comment by Zylann** [comment]
Have you seen warnings while trying to do this?

Editing across borders like this is not supported. Part of the chunks you're trying to edit are not even loaded. It's probably even supposed to do nothing.

**Comment by se8820726** [comment]
Does that mean there's no way to at least remove these walls while creating holes?

**Comment by Zylann** [comment]
You can't remove them because they don't technically "exist", they are "made up" on the fly due to the mesher falling back to the generator when it queries voxels to produce polygons.
Copy/query functions also behave like that, because they assume that "chunks without voxels but considered to be loaded are assumed to be non-edited, therefore fallback on the generator". 
In that sense, a possible workaround would be to have your own generator that returns empty chunks when querying outside of the area you want. Though it may be better for bounds to be accounted for before the generator gets invoked.

**Comment by Zylann** [comment]
I pushed a change that makes it so voxels beyond bounds are considered empty, so you no longer get "walls" when digging beyond it.
