### ISSUE TITLE
Thread dead locked when flying and mainthread is waiting the lock

### ISSUE THREAD

**Issue by lenesxy** [Zylann/godot_voxel#693]
When applicable, please describe your setup:
- Plugin version (or where you got it):https://github.com/Zylann/godot_voxel.git
mater branch:Revision: 87975a917ea7819cc5cbda1daa0f8497f62600dc
- Godot version:https://github.com/godotengine/godot/archive/refs/tags/4.3-stable.zip
- OS:Windows10
- Project:https://github.com/Zylann/solar_system_demo.git

***Screenshot***
ThreadA:
![DevCap_20240902_154905](https://github.com/user-attachments/assets/13daef3c-8968-40b1-9985-c34a2c2062a5)

ThreadB:
![DevCap_20240902_154927](https://github.com/user-attachments/assets/a9e1f998-6919-4f75-983f-a69039b917a6)

MainThread:
![DevCap_20240902_154815](https://github.com/user-attachments/assets/82058ddc-20e2-4438-bd62-ca744203bd62)

ThreadA:VoxelData::get_blocks_grid() will read lock [data_lod.map_lock] and the reference_area_block_coords() will read lock [data_lod.spatial_lock] in sl->lock_read(). Should Spatial lock need to be locked first here?
ThreadB:VoxelData::unload_blocks() will write lock [lod.spatial_lock] and then write lock [lod.map_lock]

This may cause dead lock

**Comment by Zylann** [comment]
> ThreadA:VoxelData::get_blocks_grid() will read lock [data_lod.map_lock] and the reference_area_block_coords() will read lock [data_lod.spatial_lock] in sl->lock_read(). Should Spatial lock need to be locked first here?

If both the map and the spatial lock need to be locked (i.e access to chunks AND voxels inside the chunks are both needed), then spatial lock must be locked first, and the map second while the spatial lock is acquired.

`VoxelData::get_blocks_grid` and `reference_area_block_coords` look wrong because they do the opposite, the map is locked first and spatial lock second, hence the possible deadlock.
I don't recall why it ended up this way, but should probably be swapped.

**Comment by Zylann** [comment]
Should be fixed in 5da379d10004c6726ae43f7d43cfc6d5e3bc797e
