### ISSUE TITLE
Questions about copy_block_and_neighbors()

### ISSUE THREAD

**Issue by lenesxy** [Zylann/godot_voxel#697]
I cannot understand why these three places don't need a read lock of VoxelData::Lod::spatial_lock and a read lock of VoxelData::Lod::map_lock when accessing VoxelData's VoxelDataBlock:
https://github.com/Zylann/godot_voxel/blob/87975a917ea7819cc5cbda1daa0f8497f62600dc/meshers/mesh_block_task.cpp#L80
https://github.com/Zylann/godot_voxel/blob/87975a917ea7819cc5cbda1daa0f8497f62600dc/meshers/mesh_block_task.cpp#L99
https://github.com/Zylann/godot_voxel/blob/87975a917ea7819cc5cbda1daa0f8497f62600dc/meshers/mesh_block_task.cpp#L125

And why this place has a read lock of VoxelData::Lod::spatial_lock but doesn't need a read lock of VoxelData::Lod::map_lock when copy from VoxelData's VoxelDataBlock:
https://github.com/Zylann/godot_voxel/blob/87975a917ea7819cc5cbda1daa0f8497f62600dc/meshers/mesh_block_task.cpp#L151

**Comment by Zylann** [comment]
`MeshBlockTask` doesn't actually looks up maps of `VoxelData`, that step is done up-front when the task is created. It doesn't need to be locked again.
The `blocks` span is from an array owned by the task, it doesn't need locking.
As for `VoxelDataBlock`, they aren't involved here. Only shared_ptrs to `VoxelBuffer` are used. These should be safe to access even if corresponding blocks are removed from the map in the meantime. The thread will simply potentially hold the last reference and finish meshing on stale data (which might eventually get ignored when the result is returned).
SpatialLock is still used because it synchronizes access to the contents of `VoxelBuffer`.

**Comment by MGilleronFJ** [comment]
> The blocks looks like has a pointer to VoxelBuffer, not a copy of VoxelBuffer.

It is a *shared_ptr*, not a raw pointer. That's a big difference here. `shared_ptr` is reference-counted, and that refcount is thread-safe.

> When copy_block_and_neighbors() is called the VoxelData is being copied

Nope, again, `MeshBlockTask` does not query blocks from `VoxelData`, that already happened. It is used for other things like getting block size or using the spatial lock. When it comes to accessing voxels of already-acquired `shared_ptr<VoxelBuffer>`, only spatial lock is needed.

> If another thread is writing the VoxelData, would the data copied(reading) here be inaccurate?

If another thread writes to *voxels* that `MeshBlockTask` is reading, then either of the two threads will block on the spatial lock.
If no voxels are modified but instead *the blocks themselves* are replaced or removed from `VoxelData`, then `MeshBlockTask` will run on stale data, which might waste a bit of time, but is fine.
