### ISSUE TITLE
Cube texture rotations seem wrong, even in voxelgame example project

### ISSUE THREAD

**Issue by AmyGilhespy** [Zylann/godot_voxel#699]
**Describe the bug**
Rotations do not orient all faces correctly, even in the voxelgame example project.

**To Reproduce**
1. Go to the voxelgame example project, multipass_generator/blocky_library.tres
2. Click on log
3. Rotate it around in the inspector
4. See that the rotations are not correct for a log

See also https://github.com/Zylann/godot_voxel/issues/694 which may be related.

**Expected behavior**
The texture should rotate with the cube.  For the log in the example project, the lines should face the rings no matter the orientation.

**Screenshots**
![image](https://github.com/user-attachments/assets/2c60737b-9668-4218-912b-9360d6b253c8)
![image](https://github.com/user-attachments/assets/c187fe32-5fa9-4baf-b44f-e8cd6a0a08cf)

**Environment**
- OS: Windows 10
- Graphics card: Intel - Intel(R) UHD Graphics 620 (but tested on several computers with differing hardware)
- Godot version 4.3.1-rc custom build
- Module version 0417f38 I think (Github master branch on Aug 22, 2024)
- Renderer used: Compatibility

Godot Engine v4.3.1.rc.mono.custom_build - https://godotengine.org
OpenGL API 3.3.0 - Build 27.20.100.9749 - Compatibility - Using Device: Intel - Intel(R) UHD Graphics 620

**Comment by Zylann** [comment]
I'm not sure why, because I thought rotation would not need to touch UVs (or any other attribute attached to specific vertices) and only needs to affect positions and normals, but the problem maybe comes somehow from the fact UVs are gathered *after* rotation?

Rotation is done here: 
https://github.com/Zylann/godot_voxel/blob/87975a917ea7819cc5cbda1daa0f8497f62600dc/meshers/blocky/voxel_blocky_model_mesh.cpp#L229

And UVs are gathered in either of these places:
https://github.com/Zylann/godot_voxel/blob/87975a917ea7819cc5cbda1daa0f8497f62600dc/meshers/blocky/voxel_blocky_model_mesh.cpp#L337
https://github.com/Zylann/godot_voxel/blob/87975a917ea7819cc5cbda1daa0f8497f62600dc/meshers/blocky/voxel_blocky_model_mesh.cpp#L371

**Comment by Zylann** [comment]
I checked the voxelgame demo, but I could not reproduce what you had.

However I noticed you didn't look at the blocky_game demo. So I had another look...
And it turns out the log model in the multipass demo is *not* a mesh model, it's a *cube* model.
`VoxelBlockyModelCube` rotation is implemented differently. It doesn't rotate the model, it rotates the faces on which textures are projected (by changing the `cube_tiles` property). Basically, it's not true rotation. This also goes for the "height" property, which is always applied to the top.

**Comment by AmyGilhespy** [comment]
That makes sense.  The reason I mentioned the multipass demo is indeed that it was the example that used the cube models, which we are trying to use in our project.

In our project, we are trying to make logs that rotate axially, but using the cube models it doesn't do a true rotation as you mentioned.  If this is on purpose, is there any way around it with a cube model or should we switch to mesh models for things that rotate such as logs and such?  As long as the performance is still good I'm not against switching to mesh models in my project -- the reason I chose cube models is because I assumed (without any testing!) that cube models would be more performant than mesh models where the model is just a cube anyway.  If they are the same or similar then there's no need for us to use cube models in our project.

I just wonder what the use case of the cube model's rotation/direction/axial properties are if they aren't true rotations, as they seem hard at present to use for any real purpose in an actual game.  Maybe I'm missing something here.

Thanks for your comments and explanation!  I love your work on voxel tools.  Keep it up! <3

**Comment by Zylann** [comment]
> If this is on purpose, is there any way around it with a cube model or should we switch to mesh models for things that rotate such as logs and such?

Currently you'd have to use mesh models. There is virtually no difference using one or the other in terms of performance.

> I just wonder what the use case of the cube model's rotation/direction/axial properties are if they aren't true rotations

Cube models mostly exist as a shortcut so modeling is not necessary. Also, they *don't* have rotation/direction/axial properties. the buttons rotate the setup of tiles instead.

**Comment by AmyGilhespy** [comment]
Thank you so much for the explanation!  Take care.

**Comment by Zylann** [comment]
I just pushed a change that make rotation work the same with VoxelBlockyModelCube 01f8a1e9f7aad871580610522f3b7e5a8c74ceb0
