### ISSUE TITLE
Sampling VoxelGeneratorGraph containing sqrt() ops produces incorrect results.

### ISSUE THREAD

**Issue by Illauriel** [Zylann/godot_voxel#717]
In one test project I was using a Distance2D node to suppress terrain height and make an island. I have a script for sampling surface height, and I've noticed that beyond certain distance it produces incorrect values (-99.9 in my case) for the whole block.

I tried to narrow it down to see where the problem occurred. I first thought it's a division node and replaced it with multiplication. Same result. 

Then I tried to replace Distance2D node with actual distance calculation.
![Screenshot 2024-12-04 022220](https://github.com/user-attachments/assets/df732370-3df0-441f-81ff-92c507dce980)
![Screenshot 2024-12-04 022100](https://github.com/user-attachments/assets/5f16dd71-936d-466e-a101-484c76647d51)
The result was also the same.

Buuut, when I replaced Sqrt node with Pow 0.5, it magically worked.
![Screenshot 2024-12-04 022026](https://github.com/user-attachments/assets/ebc89ae4-73ae-4cf2-935f-1c5bbeaa505a)

Best part is all of these setups actually produce valid meshes, so it only happens if you use generate_block() to get a buffer of values. 

I can try producing MRP if it will help, but was a bit short of time at the moment of posting^^'

**Environment**
- OS: Win 11
- Nvidia RTX 3060 Laptop
- Godot Engine v4.3.1.rc.custom_build
- Module version (eca2aaa8bb07614f2e9d1ef436156d0a5da55ff3)
- Forward+

**Comment by MGilleronFJ** [comment]
I didn't do detailed investigation yet, but after an early quick look at how sqrt is implemented, I could not find anything obvious. 

My current suspicion is that you're simply hitting a side-effect of SDF clipping, which is an optimization `generate_block` does when it finds that a whole block either has SDF>0 or SDF<0. In such cases, it fills the block with a constant "far away" or "into ground" instead of calculating every voxel. This indeed means that if you sample voxels inside the area and it ends up using the generator (which is what happens also in VoxelLodTerrain if you haven't edited the area) you will get different values than what a full calculation would yield. The point is rather that these values have the same sign and might be somewhat distant from 0.
If that's what happens, then this is by design. If you really want the generator to always produce exact values for SDF, you may turn off this behavior by setting `[sdf_clip_threshold](https://voxel-tools.readthedocs.io/en/latest/api/VoxelGeneratorGraph/#i_sdf_clip_threshold)` to be very high. That will impact performance though.

**Comment by Illauriel** [comment]
Brilliant! setting sdf_clip_threshold to high number works, and since I need to sample height only seldomly, I can set it to high number for the duration of sampling and then set it back to default. So it wasn't a bug after all^^  

> The point is rather that these values _have the same sign_ as what a full calculation would give

Ah, makes sense! Outside the 512 radius would be exactly where the values get into negatives. 
And I've noticed that Pow has -inf..inf in the range analysis and was a bit confused why it worked whereas Sqrt had actual proper ranges and didn't work. x)

Thanks a lot!

**Comment by MGilleronFJ** [comment]
> since I need to sample height only seldomly, I can set it to high number for the duration of sampling and then set it back to default

There is a bit of a caveat of doing that: 
Setting the property might cause perturbations in the consistency of generated chunks because it could be running in different threads as you're doing that. So currently you either have to guarantee that case doesn't occur (but it's hard), or you have to use a duplicate, or you shouldn't change it.
If that's a problem it might be possible to pass a flag to the method so it only affects the current invocation and not the settings themselves.
