### ISSUE TITLE
How do I get smooth voxel data.

### ISSUE THREAD

**Issue by PiCode9560** [Zylann/godot_voxel#723]
I'm using VoxelTool.grow_sphere(...) to dig holes into smooth voxel. I want to get the voxel index and weight data to check how much of what is collected.

How do I get the voxel data? Or even better, how do I check how much of what are mined?

**Comment by Zylann** [comment]
I don't see how your question relates to your issue title, but calculating how much has been removed or added by an operation is currently not built-in, so you would have to figure it out by making a copy of the area using the `copy` function, before and after, and then use a 3D for loop over the two buffers to find the differences.
I don't have a perfect solution for this. I might eventually add a counting method which would be based on how many *discrete* voxels crossed from a SDF<0 to SDF>0, but I have no idea how to implement something more precise (like exact "volume" change) without precision errors or confusing calculations (since smooth voxels store a signed distance, not an "amount of stuff").

**Comment by PiCode9560** [comment]
I think I figured out the whole `VoxelBuffer` things. Now I can compare the SDF before and after mining to get the amount destroyed, and also got the material index to see what is destroyed. This is exactly what I'm looking for. Thanks.

By the way, in my comment above, I meant to say SDF not weight.

I guess this issue can be close now.
