### ISSUE TITLE
pixel height question

### ISSUE THREAD

**Issue by drarem** [Zylann/godot_voxel#77]
how would i find the height of a given pixel on the heightmap and place a mesh at the location (in 3D)?

**Comment by Zylann** [comment]
This is a voxel terrain, no heightmap is stored anywhere. One of the generators uses an image as a heightmap but it's not really designed to spawn meshes.

What you probably want is to find the highest voxel at a specific (x,z) position, which you can do by either iterating downwards getting voxels until you find a non-air one, or use a normal physics raycast.

**Comment by tinmanjuggernaut** [comment]
It's pretty easy to determine the height by just playing a demo and going to look at the terrain in game, by looking at the value on the heightmap, or the correct way: with raycasts.

1. Each X,Z pixel on the heightmap corresponds to a grid position. So the voxel space goes from 0,0 to 1024,1024 on XZ, then repeats. You can take your player in game to any position, say x=591, z=486 and see the height is 147.

1. You can open up the heightmap in photoshop and look at the values for each position. So 200,385 is pure white (255), and 155,425 is pure black (0). Moving my player there in game, I see the height values are 150 and -50 respectively. So the color values 0-255 map to -50 - 150. Simple algebra will allow you to convert any value.

1. However, since the terrain is modifiable, the right way to get the true height is to shoot a raycast vertically down (Vector3(0,-1,0)) at your location and the engine will tell you the exact height of the mesh.

1. Or as Zylann says, iterate through voxels. That's for a blocky terrain though. On a smooth terrain, you might have a mesh that is only halfway through a grid position, so raycasts are the best, most accurate method.

**Comment by Zylann** [comment]
Closing, as question got answered but went stale

**Comment by tinmanjuggernaut** [comment]
This and some other answers to tickets should eventually make their way into the docs, as FAQs.
