### ISSUE TITLE
VoxelTerrain does not work with NoiseStream

### ISSUE THREAD

**Issue by SnailBones** [Zylann/godot_voxel#80]
I'm on Windows 10 using Godot 3.2.

Following the documentation, I am unable to get VoxelTerrain working with a NoiseStream. I have tried in both editor and code. VoxelLodTerrain works, but the same code applied to VoxelTerrain  produces an empty world.

Here I attempt to add VoxelStreamNoise in GDScript. The object has been assigned a material and viewer_path in the Inspector.

```
func _ready():
	voxel_library = VoxelLibrary.new()
	stream = VoxelStreamNoise.new()
	stream.noise = OpenSimplexNoise.new()
	stream.noise.seed = randi()								# Int (0): 		0 to 2147483647
	stream.noise.octaves = 1+randi()%5						# Int (3): 		1 - 6
	stream.noise.period = rand_range(0.1, 256)				# Float (64): 	0.1 - 256.0
	stream.noise.persistence = randf()						# Float (0.5): 	0.0 - 1.0
	stream.noise.lacunarity = rand_range(0.1, 4)			# Float (2): 	0.1 - 4.0
```

**Comment by tinmanjuggernaut** [comment]
Blocky + 3D noise doesn't work. @Zylann will have to explain why. My demo demonstrates every combo that works by code:

https://github.com/tinmanjuggernaut/voxelgame/blob/master/project/fps_demo/scripts/CodeTerrain.gd

**Comment by Zylann** [comment]
`VoxelStreamNoise` doesn't support blocky worlds, that's only because it outputs to `ISOLEVEL` channel. It should output to `TYPE` channel instead and be told which type of the library to set for non-air voxels.

As for in the editor, terrain generation is turned off in here, for security reasons, because right now it's not entirely thread-safe and not really updating right when changes are made. Will need to be worked on in the future.

**Comment by tinmanjuggernaut** [comment]
@Zylann I don't think this should be tagged as C#.

**Comment by tinmanjuggernaut** [comment]
3D noise has been added to blocky in the above PR.

![image](https://user-images.githubusercontent.com/632766/72161661-7b7fc380-33fb-11ea-8054-d891d6795936.png)
