### ISSUE TITLE
Native c++ and C#

### ISSUE THREAD

**Issue by sevensidedmarble** [Zylann/godot_voxel#89]
Now that there's first class c++ and C# scripts in Godot is there any chance of being able to implement this plugin with that so that the compiling from source step isn't needed?

Would C# scripts be as fast as the current approach?

**Comment by tinmanjuggernaut** [comment]
I can safely say there's no chance Zylann will rewrite the module in C#. However your C# code can call the module. 

C# has been measured at 2 - 7.5 times slower than C++. 
http://www.royaldonut.games/2019/03/29/cpu-voxel-benchmarks-of-most-popular-languages-in-godot/

Converting the module to a plugin remains a possibility in the future, but it's low priority. 

Rebuilding the engine with the module compiled is really no big deal for one who is becoming a game developer. However it is no longer a requirement:
https://www.youtube.com/watch?v=zfzmcbR1H_0

**Comment by Zylann** [comment]
I am considering "librarizing" the module in the far future so that it can have a GDNative implementation, but currently GDNative symbols don't get represented in C# (i.e you have to use reflection to call it). A P/Invoke-ready build could work too for a library but all this is pretty much far in the future. I'm not considering porting to C# at all because it would just make it slower and too much work.
Having it as a module right now is a good compromise, as all languages and platforms can use it without hassle apart from engine compilation, which is not a big deal anyways since @tinmanjuggernaut gracefully provides such builds now.

**Comment by Sevensidedmarble** [comment]
I know C# code in Godot will sit somewhere between C++ and GDScript in terms of speed, but I was curious if that would be "enough" to make a good implementation.

**Comment by tinmanjuggernaut** [comment]
To write your game in C# and call this module will be quite performant. To rewrite the module as C# is not worth your time. It will be 2-7.5x slower and it's already not as fast as we'd like, though decent. There are gdscript implementations of blocky voxels around. But smooth voxels are quite taxing.

**Comment by blockspacer** [comment]
If you will convert the module to a plugin - support for some platforms (like HTML5) will be lost

**Both GDNative and C# are not supported for HTML5 export.**

BTW godot_voxel may work fine in HTML5 with threads disabled (or `web workers` and `shared memory` manually enabled in browser settings). I made `godot_voxel` work in browser long time ago and planning to add HTML5 support. https://github.com/godotengine/godot/issues/12699#issuecomment-521589396

If you want fast prototyping with C++ modules without recompiling - please try `Cling` for `dev` builds https://github.com/godotengine/godot/issues/31630#issuecomment-574600685

**Comment by Zylann** [comment]
Superseded by https://github.com/Zylann/godot_voxel/issues/333
