### ISSUE TITLE
Higher depth of voxel values

### ISSUE THREAD

**Issue by voxelbec** [Zylann/godot_voxel#91]
This engine looks great for a voxel project I have in mind except for the 8bit voxel storage channel size. Is it possible to increase the number of bits defining each voxel without resorting to invoking other entity objects? I have in mind a world where voxels represent pseudo-molecules of which there would be a great variety.

**Comment by Zylann** [comment]
I have plans to allow 16-bit depth, but how much do you need exactly? Currently you can use multiple channels instead of one.

**Comment by voxelbec** [comment]
My concept for the sub-voxel chemistry involved a 5x5 rectilinear grid populated with almost any combination of 64 distinct atoms and their respective bond states but this would require multiple times the planned 8x16bits to represent (I estimate around 1kbit depending how things are encoded). I realise this likely asking too much of an efficient voxel engine.

I have pondered alternatives and could instead perhaps use a smaller isometric grid and 32 distinct atoms to fit within 8x16bits but it will be very tight.

Would 8x32bits or 16x16bits be possible? Doubling the planned limit would open a lot of opportunities for sub-voxel weirdness in the engine.

PS: Thanks for making this project, it looks like the most accessible voxel dev opportunity around for a coding noob like myself.

**Comment by Zylann** [comment]
I did not plan for voxels to be that large for a given channel. I was considering supporting 1, 8, 16, 24 and 32 bit voxels, not more. Beyond that, if you dont use channels, it goes into not-so-voxel territory. The engine would not even know what to do with the chemistry you put in there, it would barely be storage, something you could do without this module. With 32 bit you could already store a pointer to an object of whatever size you want, rather than the object directly. Also, if a voxel is empty, its size remains 32 bits, which is easily wasted in empty spaces near used voxels.

**Comment by voxelbec** [comment]
So if i understand correctly:

Your plan to provide 16bits per channel for the 8 channels amounts to 128bits of information per voxel however 2 of those channels will be used by the engine leaving 96bits free for arbitrary storage?

My plan was to fit my sub-voxel chemistry data into the direct voxel data space rather than resort to pointers as my world will require a _lot_ of block updates that query neighbouring voxels and I assumed such abstractions would be computationally demanding en-mass.

**Comment by Zylann** [comment]
> 2 of those channels will be used by the engine leaving 96bits free for arbitrary storage?

No, when a channel isn't used it can get compressed to a single value as in "all values in this channel are the same".
When I said that empty voxels still take space, I meant it for a channel that has *some* used voxels in it.

**Comment by voxelbec** [comment]
Apologies for all the questions and thanks for your patience.
How many bits per voxel does your planned 8x16bit expansion provide after engine overhead has been subtracted (assuming engine is in blocky mode)? I'll work with what i'm given but i'm a bit unsure what exactly that is.
Thanks Zylann

**Comment by Zylann** [comment]
Currently, voxels have up to 8 channels, each being able to store 8 bit values for various purposes each. I plan to allow to set this depth to 1, 8, 16, 24, 32, or 64 bits at the very most.
This is similar to what `Image` allows you to store in Godot, except instead of the 4 RGBA channels, there are up to 8 with individual depth settings, to allow some different ranges of usage. The data channels are meant to contain are very basic and low-level, like "type", "indexed color", "distance to surface", "entity ID" or "light".

**Comment by voxelbec** [comment]
These deeper channels sound like they will suit my needs nicely.
The chemistry will be simple and bitwise in nature.
Thanks :D
