### ISSUE TITLE
smooth terrain: 'lines' on 'connection' points

### ISSUE THREAD

**Issue by blockspacer** [Zylann/godot_voxel#96]
![image](https://user-images.githubusercontent.com/35254900/72210062-eb0eb500-34c6-11ea-836b-fecb35d960e1.png)

`White dots` follows line pattern and can change on camera moment. They are more noticeable on shadowed surfaces. Light can pass through `white dots`.

Tested on Ubuntu 18.04, Nvidia, Godot voxel 1b19bbee8e2d17ee8f2c1f45435aaf1e1a6b79cf (Enable 3D noise on VoxelTerrain...), Godot 0587df4aa5f2977350cc80b1522cdc1e483c4515 (3.1.2-stable)

Project based on `noise_smooth_lod.tscn` from https://github.com/tinmanjuggernaut/voxelgame with CHANNEL_ISOLEVEL renamed to CHANNEL_SDF 

Please respond if you can't reproduce the bug

![image](https://user-images.githubusercontent.com/35254900/72210108-5e182b80-34c7-11ea-9dd1-4f79676c161a.png)

**Comment by Zylann** [comment]
I have seen cases where there are a few pixels, or sometimes even a tiny line in some places, but that was extremely rare. I don't know what the cause is. It could be a float precision error.

**Comment by blockspacer** [comment]
@Zylann

Based on quote `As a solution for visible seams or cracks along mesh edges, a method called
Transition Cubes algorithm` from paper `Examining Automatic Texture Mapping of Arbitrary Terrains` https://www.diva-portal.org/smash/get/diva2:422722/FULLTEXT01.pdf 

I assume that `seams or cracks along mesh edges` may be possible without `Transition Cubes algorithm`. Are `seams or cracks` from paper may be like `White dots`?

**Comment by blockspacer** [comment]
@Zylann 
`modular meshes are stitched next to each other` sound like Z-fighting https://youtu.be/6y72Ozcn7Eg

**Comment by Zylann** [comment]
> I assume that seams or cracks along mesh edges may be possible without Transition Cubes algorithm. Are seams or cracks from paper along mesh edges may be like White dots?

No they aren't. This module uses Transvoxel, which has transition meshes already (similar as the one seen in this paper). 

> modular meshes are stitched next to each other sounds like Z-fighting

This is not Z-fighting either. It may just be a float precision error, where one of the vertices is offset by a tiny amount for some reason. Also, it's not as simple to fix as "just moving them together" like done with simple cubes, because this is an arbitrary terrain, and chunks are polygonized in parallel, without "knowing each other". They should have just lined up instead.

In order to work fixing this, I need a small reproduction project where this problem can immediately be seen, isolated and measured.

**Comment by tinmanjuggernaut** [comment]
@blockspacer You are using Godot 3.1.2, but you're using voxel master with all updates (plus the macro patches for 3.1?)

This looks like your own shader. Are you using the vertex shader here? If so, what if you remove it? 
https://github.com/Zylann/godot_voxel/issues/2#issuecomment-570013045

**Comment by blockspacer** [comment]
@Zylann 
@tinmanjuggernaut 
Bug remained after i switched to 
godot 3.1 513bfe496c10eb874d085d009742a568363413d3 
godot_voxel master with support for godot 3.1 branch https://github.com/Zylann/godot_voxel/pull/102 
tinmanjuggernaut/voxelgame ffe4aec31f5fa286aa17bcdd614eb72e877bbd09

`your own shader` - i use triplanar.shader (default) from tinmanjuggernaut/voxelgame ffe4aec31f5fa286aa17bcdd614eb72e877bbd09
BTW - I can't notice difference after un-commenting `VERTEX = get_transvoxel_position(VERTEX, COLOR);`

`was extremely rare` - `white dots` are much more visible with darker shadows. **They can make smooth terrain almost unplayable when camera moves (critical for games that must have dark caves or day/night cycle)**. On cube terrain they still hardly noticeable, but can `blink` along connection lines when camera moves.

My shadows setup:
in WorldEnvironment - procedural_environment
**Energy - 0.1
Sky Contribution - 0.1**
in WorldEnvironment - DirectionalLight
Bake mode: Disable (BTW, inderect produced same results. Why indirect is used on dynamic terrain in tinmanjuggernaut/voxelgame? Isn't indirect for static terrain?)

**Comment by tinmanjuggernaut** [comment]
Direct Light /Indirect Energy=1? That's the default. It shouldn't any any effect without GI.

I see it. So basically @Zylann, if you turn off the lights, turn down ambient energy, you'll see a ton of white speckles twinkle along the square seams. It is effected by camera angle. Provided vertex shader doesn't help. Occurs in heightmap or noise, VLT or VT.

**Comment by blockspacer** [comment]
BTW, why in `get_viewer_pos_and_direction` line `out_direction = -gt.basis.get_axis(Vector3::AXIS_Z)` is not `.normalized()`?

**Comment by Zylann** [comment]
> why in get_viewer_pos_and_direction line out_direction = -gt.basis.get_axis(Vector3::AXIS_Z) is not .normalized()?

Because the `basis` already is.

If you see those white dots even with a totally different mesher and it's affected by lighting, then it's even harder to find out if the problem comes from my module. I have no idea what the real cause would be or how to fix it. It could even be dependent on graphics driver.

**Comment by tinmanjuggernaut** [comment]
I tried it on a November build with DMC and it doesn't appear. It's only on the new builds with Transvoxel. So we all see it, on presumably different cards and drivers, shaders and a blank material, VT and VLT, different data sources. Transvoxel seems to be the common denominator.

It's not affected by lighting. It's affected by camera angle, and even frame. They flicker even if the camera isn't moved. It's only visible in the dark though.

Here I took a clip of 334 frames, while gently moving the camera. I merged all frames together with a 'lighter color' blend mode so you can clearly see the pattern it makes. It would be on a very thin grid line, but it is sampled fatter due to my camera motion.

![image](https://user-images.githubusercontent.com/632766/72222175-f9c79b80-359c-11ea-85a7-c53f08cc9a7c.png)

Still photo. The line of dots started lower right and curved up and over the rock, though on this frame the upper portion didn't illuminate.

![image](https://user-images.githubusercontent.com/632766/72222287-f7197600-359d-11ea-9c84-f15e7f93a5ef.png)

**Comment by Zylann** [comment]
> I tried it on a November build with DMC and it doesn't appear. 

My guess is, they don't appear with DMC because marching square skirts *do extend beyond the necessary range* to fix LOD cracks. Which "luckily" avoids the dots.
With Transvoxel, the geometry is supposed to perfectly connect without off-margins of any kind. Which unfortunately uncovers the dots.

> They flicker even if the camera isn't moved. 

The few I could find did not do that Oo

**Comment by tinmanjuggernaut** [comment]
> With Transvoxel, the geometry is supposed to perfectly connect without off-margins of any kind. Which unfortunately uncovers the dots.

So maybe it's a Godot renderer bug?

**Comment by Zylann** [comment]
@tinmanjuggernaut  Yeah it's the sky, that's why I suggested dark sky to mitigate the issue. An anti-firefly effect would also help, but your screenshot is madness. I'm not seeing that many dots anywhere.

**Comment by Calinou** [comment]
> was extremely rare - white dots are much more visible with darker shadows. They can make smooth terrain almost unplayable when camera moves (critical for games that must have dark caves or day/night cycle). On cube terrain they still hardly noticeable, but can blink along connection lines when camera moves.

This could be worked around by darkening the sky when the player is detected as being in a cave. This is what [Minetest](https://minetest.net) does (it also suffers from this issue).

**Comment by blockspacer** [comment]
**Tested under Windows 10, Nvidia. Same behavior**.

If you can't reproduce - please try to:
1) use **`white_dots_bug` branch** from https://github.com/blockspacer/voxelgame/tree/white_dots_bug
2) Disable "Antialiasing" in graphics driver settings as stated in https://bugs.mojang.com/browse/MC-1794

Reprodued with godot_voxel https://github.com/blockspacer/godot_voxel/tree/3_1_without_error_macros_h (same behavior in master branch).

@Calinou
Thanks for respose, great ideas.
**Issue can be seen not only in caves. How `Minetest` handles shadowed cliffs or night/day cycle**?

**Comment by Zylann** [comment]
I tried this anti-firefly shader on a fullscreen `ColorRect`, it cleared all fireflies I was able to reproduce (will only work on isolated pixels). Of course, at performance cost.

```glsl
shader_type canvas_item;

uniform float u_threshold = 0.4;

void fragment() {
	vec3 col = texture(SCREEN_TEXTURE, SCREEN_UV).rgb;
	vec3 col_nx = texture(SCREEN_TEXTURE, SCREEN_UV - vec2(SCREEN_PIXEL_SIZE.x, 0.0)).rgb;
	vec3 col_ny = texture(SCREEN_TEXTURE, SCREEN_UV - vec2(0.0, SCREEN_PIXEL_SIZE.y)).rgb;
	vec3 col_px = texture(SCREEN_TEXTURE, SCREEN_UV + vec2(SCREEN_PIXEL_SIZE.x, 0.0)).rgb;
	vec3 col_py = texture(SCREEN_TEXTURE, SCREEN_UV + vec2(0.0, SCREEN_PIXEL_SIZE.y)).rgb;
	float d = min(
		min(distance(col, col_nx), distance(col, col_ny)), 
		min(distance(col, col_px), distance(col, col_py))
	);
	vec3 col_m = 0.25 * (col_nx + col_ny + col_px + col_py);
	//col_m = vec3(0.0, 1.0, 0.0); // DEBUG
	COLOR = vec4(mix(col_m, col, step(d, u_threshold)), 1.0);
}
```

**Comment by Calinou** [comment]
> How Minetest handles shadowed cliffs or night/day cycle?

It can also detect when you're looking at a large surface with a low light level (though the algorithm isn't perfect).

**Comment by blockspacer** [comment]
@Zylann 
`isolated pixels` - bug may produce lines. Also it may produce small `holes` in shadow (very rarely)
I tried FXAA shader from https://github.com/blockspacer/voxelgame/commit/614be8a190c968c39a5ef17a91661ed68eae702e and it made `white lines` hardly noticeable (as a temporary wokaraund). 

`quantize world position of vertices in the vertex shader` - I'd like to try that approuch, but IDK where to start.

**Comment by Zylann** [comment]
Isolated pixels is all I could reproduce, so that fixed it at least for me I guess.
To quantize in world space I guess you'd need to change the shader to calculate world space vertex positions itself (instead of Godot automatically doing it), I don't remember the keyword for that though. Then for XYZ, multiply by N, floor the result, and divide back by N (or something like that).

**Comment by blockspacer** [comment]
@Zylann 

i tried `render_mode skip_vertex_transform` to made terrain look blocky by `floor` and `N=1.0`, issue still here. I'm not sure that understood you correctly.

```
void vertex() {
	mat4 inv_model_view_matrix = inverse(MODELVIEW_MATRIX);
	
	VERTEX = floor(VERTEX.xyz);
    VERTEX = (MODELVIEW_MATRIX * vec4(VERTEX, 1.0)).xyz;
    NORMAL = (MODELVIEW_MATRIX * vec4(NORMAL, 0.0)).xyz;
	
	vertex_normal = NORMAL;

    TANGENT = vec3(0.0,0.0,-1.0) * abs(NORMAL.x);
    TANGENT+= vec3(1.0,0.0,0.0) * abs(NORMAL.y);
    TANGENT+= vec3(1.0,0.0,0.0) * abs(NORMAL.z);
    TANGENT = normalize(TANGENT);
    BINORMAL = vec3(0.0,1.0,0.0) * abs(NORMAL.x);
    BINORMAL+= vec3(0.0,0.0,-1.0) * abs(NORMAL.y);
    BINORMAL+= vec3(0.0,1.0,0.0) * abs(NORMAL.z);
    BINORMAL = normalize(BINORMAL);

    A_uv_power_normal=pow(abs(NORMAL),vec3(A_tri_blend_sharpness));
    A_uv_power_normal/=dot(A_uv_power_normal,vec3(1.0));
    A_uv_triplanar_pos = (inv_model_view_matrix * vec4(VERTEX, 1.0)).xyz * float(A_uv_tiles) / (16.) + A_uv_offset;			//On VoxelTerrain 16 is 100% size, so uv_tile is multiples of 16. 
	A_uv_triplanar_pos *= vec3(1.0,-1.0, 1.0);
	
    B_uv_power_normal=pow(abs(NORMAL),vec3(B_tri_blend_sharpness));
    B_uv_power_normal/=dot(B_uv_power_normal,vec3(1.0));
    B_uv_triplanar_pos = (inv_model_view_matrix * vec4(VERTEX, 1.0)).xyz * float(B_uv_tiles) / (16.)  + B_uv_offset;
	B_uv_triplanar_pos *= vec3(1.0,-1.0, 1.0);
	

	// Get the distance from camera to VERTEX (VERTEX as if the camera is 0,0,0)
	vertex_distance = (PROJECTION_MATRIX * MODELVIEW_MATRIX * vec4(VERTEX, 1.0)).z;		
}
```

**Comment by Zylann** [comment]
@blockspacer when I mentionned "blocky mesher" I assumed this would reproduce with blocky terrain, however when re-reading messages I must have misread that. 

If you still get the dots by flooring vertex positions *which would still be lining up without holes* then I don't know what could possibly be done.
I tried it myself, both with just `floor(VERTEX)` and `floor(VERTEX * 100) * 0.01`, none of them was problem-free.

**Comment by Zylann** [comment]
Does this ever happens within LOD0? (i.e not at transitions, and not above LOD0)

**Comment by tinmanjuggernaut** [comment]
I filed an upstream bug with details from here.

**Comment by blockspacer** [comment]
Great articles about T-junction problems
https://blackflux.wordpress.com/2014/02/23/meshing-in-voxel-engines-part-1/
https://blackflux.wordpress.com/2014/03/01/meshing-in-voxel-engines-part-2/
https://blackflux.wordpress.com/2014/03/02/meshing-in-voxel-engines-part-3/

Also interestiong idea from
https://www.reddit.com/r/VoxelGameDev/comments/3muuee/rendering_is_missing_pixels_possibly_t_junction/
> It is sometimes a feasible approach not to clear the color buffer and so "smear" over those pixels (popularized by the quake engines).

**Comment by Zylann** [comment]
AFAIK Transvoxel does not produce T-junctions.

**Comment by blockspacer** [comment]
I tried to add to https://github.com/tinmanjuggernaut/voxelgame/blob/master/project/fps_demo/scripts/Player.gd
```
func _ready():
	$CamNode.get_viewport().set_clear_mode(Viewport.CLEAR_MODE_NEVER)
	$CamNode/Camera.get_viewport().set_clear_mode(Viewport.CLEAR_MODE_NEVER)
	print('Player ready')
```
Nothing changed. Sky is visible. 'Player ready' printed to console

**Comment by Zylann** [comment]
@blockspacer I don't know, maybe the sky acts as a clear, or maybe it doesn't work for the main viewport

**Comment by Calinou** [comment]
@blockspacer Try changing the background mode to **Keep** in the Environment resource attached to the WorldEnvironment node.

**Comment by blockspacer** [comment]
Keep mode fixes issue both with or without `set_clear_mode(Viewport.CLEAR_MODE_NEVER)`

**Comment by tinmanjuggernaut** [comment]
A workaround has been found. https://github.com/godotengine/godot/issues/35067#issuecomment-1058617216

Adding this to the shader will fix the fireflies along the seams of the voxel terrain meshes. 

```
shader_type spatial;
render_mode  skip_vertex_transform;

void vertex() {
	VERTEX = (WORLD_MATRIX * vec4(VERTEX, 1.0)).xyz;
	VERTEX = (INV_CAMERA_MATRIX * vec4(VERTEX, 1.0)).xyz;
}
```

However, since we're all using triplanar-mapping, specifying `skip_vertex_transform` messes up NORMAL, so when you move the camera around the terrain gets lighter and darker.

This page says how the NORMAL projection (and binormal/tangent) can be done manually, but it's wrong. This works for VERTEX, but not NORMAL.
https://docs.godotengine.org/en/3.4/tutorials/shaders/shader_reference/spatial_shader.html?highlight=skip_vertex_transform#render-modes

```
Users can disable the built-in modelview transform (projection will still happen later) and do it manually with the following code:

shader_type spatial;
render_mode skip_vertex_transform;

void vertex() {
    VERTEX = (MODELVIEW_MATRIX * vec4(VERTEX, 1.0)).xyz;
    NORMAL = normalize((MODELVIEW_MATRIX * vec4(NORMAL, 0.0)).xyz);
    // same as above for binormal and tangent, if normal mapping is used
}
```

We have two triplanar mapping algorithms, one made by zylann in his `dmc_terrain.shader` and one made by me, adapting the one built into Godot `triplanar.shader`. Both are negatively affected by `skip_vertex_transform`. I'm not yet sure how to fix the projection on NORMAL so it works for triplanar mapping.

**Comment by tinmanjuggernaut** [comment]
Looks like it does work if done correctly. This is now the working vertex shader for `dmc_terrain.shader` using zylann's triplanar method. The three bottom lines are the additions, plus the render mode. The key is the new lines must go at the end, not at the top.

```
render_mode  skip_vertex_transform;

void vertex() {
	v_world_pos = VERTEX;
	v_world_normal = NORMAL;
	
	VERTEX = (WORLD_MATRIX * vec4(VERTEX, 1.0)).xyz;
	VERTEX = (INV_CAMERA_MATRIX * vec4(VERTEX, 1.0)).xyz;
	NORMAL = (MODELVIEW_MATRIX * vec4(NORMAL, 0.0)).xyz;
}

```

And this goes at the very end of my shader vertex function in `triplanar.shader`:
```
	VERTEX = (WORLD_MATRIX * vec4(VERTEX, 1.0)).xyz;
	VERTEX = (INV_CAMERA_MATRIX * vec4(VERTEX, 1.0)).xyz;
	NORMAL = (MODELVIEW_MATRIX * vec4(NORMAL, 0.0)).xyz;
	TANGENT = (MODELVIEW_MATRIX * vec4(TANGENT, 0.0)).xyz;
	BINORMAL = (MODELVIEW_MATRIX * vec4(BINORMAL, 0.0)).xyz;
```

I believe this ticket can now be closed after over 2 years!

**Comment by blockspacer** [comment]
@tinmanjuggernaut Thank you!
