### ISSUE TITLE
Voxel metadata

### ISSUE THREAD

**Issue by Zylann** [Zylann/godot_voxel#98]
Voxels alone can store a very limited set of data. Even if we have up to 8 channels available with soon an option to choose how many bits they have each (between 1 and 64), they are not fit for more complex data such as strings, arrays or data dictionaries. Also, channels are fit for frequently used data. If they get used for rare data, it would waste memory.

Such metadata would largely be unused by the module, but more up to your game to interpret and use.

### Voxel metadata

This allows, for specific voxels, to store aribtrary data (most of what can fit in `Variant`) for individual voxels. It could be accessed the same way, only with a different function, like so:

```gdscript
var items = voxel_tool.get_voxel_metadata(chest_position)
items.append({"type": "arrows", "count": 64})
voxel_tool.set_voxel_metadata(chest_position, items)
```

Of course, this may be used sparingly, as this metadata is often much heavier than voxels. It would be stored in the block as a dictionary, mapping voxel position to the piece of data.

### Block metadata

While it would probably have less uses, I would also add per-block metadata. This would allow to store even more aribtrary data, tied to a block, not a particular voxel. Such data could be things like "visit count", "average temperature", biomes, cached fluid states or an array with tree positions.
Doing this one may need to have a block access API though.

### Access by VoxelStream

Because such metadata is tied to voxels and blocks, it means it can be generated, loaded and saved by voxel streams. This is very handy when you want to include more than just voxels to the generating process, such as trees, storage chests or NPC locations. And of course, allows this data to be saved next to voxels when using a file-based stream.

**Comment by Zylann** [comment]
Closing as this feature is implemented

**Comment by WithinAmnesia** [comment]
"Access by VoxelStream

Because such metadata is tied to voxels and blocks, it means it can be generated, loaded and saved by voxel streams. This is very handy when you want to include more than just voxels to the generating process, such as trees, storage chests or NPC locations. And of course, allows this data to be saved next to voxels when using a file-based stream."
How do we do this one in multiplayer? Are there examples? Has anyone demonstrated and tested this? What must be done to do this in Blockygame for the community benefit from? How do we do NPCs and storage chests and user account data storage like inventories can banks with Blocklygame demo so we can make more games with working examples that play well with your massive Godot systems and multiplayer?

**Comment by Zylann** [comment]
> How do we do this one in multiplayer?

I think it's just sent alongside voxels normally.

> Are there examples?

Not yet. Haven't got the time to make one.

> Has anyone demonstrated and tested this? 

Not to my knowledge.

> What must be done to do this in Blockygame for the community benefit from?

Spend time on it, which personally I dont have because of many other things, so unless someone else figures things out themselves, it will be done when I get to do it, no ETA

> How do we do NPCs and storage chests

Storage chests can be some metadata that's just an array of items, which you can recognize as being chest inventory if the type of the voxel is a certain value. NPC is more complicated. Currently there is no entity system, you have to build this yourself using signals and virtual methods exposed by terrain nodes so you can hook up to chunk load/unloads. I'm thinking of it but got nothing solid yet.

> and user account

Not in the scope of this project

**Comment by WithinAmnesia** [comment]
> > How do we do this one in multiplayer?
> 
> I think it's just sent alongside voxels normally.

Okay that is good to hear and get some confirmation for too. that should simplify things a lot by having everything already be together to work on.

> > Are there examples?
> 
> Not yet. Haven't got the time to make one.
I'll try to make an example and share it as I work to prototype entities and storage systems.

> > Has anyone demonstrated and tested this?
> 
> Not to my knowledge.
I should work on getting this be a first then we can have things be in a better position for everyone with working multiplayer entities and storage system. 

> > What must be done to do this in Blockygame for the community benefit from?
> 
> Spend time on it, which personally I dont have because of many other things, I do this on my free time, so unless someone else figures things out themselves, it will be done when I get to do it, no ETA
Okay I will start spending time on this and aiming to make incremental progress and I think when its in a highly working state share the multiplayer entities and storage systems with the community so everyone can benefit. Bit by bit.

> > and user account
> 
> Not in the scope of this project
That is perfectly good too. We already have working multiplayer player inventories. So it seems to be a matter of database and server work. We already have a great start to expand upon in the Blockygame demo's individual player inventories. This can be solved with conventional means and I think there are enough community resources and personal to solve this bit by bit as its own puzzle after this one in order of importance. So as to get the entities and storage systems working first. If we can get multiplayer chunk data to save chest / storage data we are 4/5 the way there and that is a massive success. In that case it would be like real life where everything is accessible in the open-world. So then it becomes a social matter. Yet even then we are at ~4/5 solved for player account data storage. So as long as the chunks / storage systems work and save with the multiplayer chunk data. Meaning that the storage data be saved and load and unload fine in the voxel server chunk data system and work good with the multiplayer and chunk streaming we have a massive success.

> > How do we do NPCs and storage chests
> 
> Storage chests can be some metadata that's just an array of items, which you can recognize as being chest inventory if the type of the voxel is a certain value.
So with chests its a matter of of testing / prototyping / working with Voxel Metadata and in thoery it should eventually work with enough tinkering and testing with what is already there with what is there to work with Voxel metadata systems in the Blockygame demo? So for Chests to get working just tinker away with Voxel metadata values, add a modified inventory interface and when the chest block is destroyed it drops all blocks onto the ground as items to pick up type of thing? As in it should be possible to copy the minecraft style of chest in Blockygame demo with enough work with the voxelmetadata systems that are already there? https://github.com/Zylann/godot_voxel/issues/98

There probably needs to be when block breaks it drops a item that can be picked up. Also the chest when broken should drop all contained items like in Minecraft. Does Blockygame already support / have examples of when the blocks are broken they turn into items that can be collected by the player or must this be made too?

>  NPC is more complicated. Currently there is no entity system, you have to build this yourself using signals and virtual methods exposed by terrain nodes so you can hook up to chunk load/unloads to know when they should spawn/despawn. I'm thinking of it but got nothing solid yet.

"Signals and virtual methods exposed by terrain nodes so you can hook up to chunk load/unloads to know when they should spawn/despawn."
Can we cheat a tiny bit and use a spawner block like in Minecraft to get this Entity business alive and off the ground a bit? As in can Voxel_metadata be used to make a spawning block / voxel than can say spawn an entity when loaded by the voxel streamer? Like spawn 'test_entity1'#1

**Comment by WithinAmnesia** [comment]
https://github.com/Zylann/voxelgame/blob/2147d8152ac860c616b764786f736e0cd7a4d844/project/blocky_game/blocks/blocks.gd#L43
points to:
https://github.com/Zylann/voxelgame/blob/2147d8152ac860c616b764786f736e0cd7a4d844/project/blocky_game/blocks/voxel_library.tres#L11C1-L11C115
How are we to add more blocks if the data is not human readable in parts?
"[ext_resource type="ArrayMesh" uid="uid://dm05scqbatw2v" path="res://blocky_game/blocks/planks/planks.obj" id="7"]"
Like mate how does a regular person understand how to use this?
[ext_resource type="ArrayMesh" uid="**_uid://dm05scqbatw2v_**" how do make more of those?

This works: "path="res://blocky_game/blocks/planks/planks.obj" id="7"]"" regular people can use that but how on earth are people going to more more "uid://dm05scqbatw2v" parts?

Also where are the textures?
![image](https://github.com/Zylann/voxelgame/assets/86871191/9d14b03d-8ad8-4165-be23-3403bfe0f55b)
OH
![terrain](https://github.com/Zylann/voxelgame/assets/86871191/014db9e2-04bb-41c5-91ed-0e9c3166865f)
Then how does all work together?

So we have:
https://github.com/Zylann/voxelgame/blob/2147d8152ac860c616b764786f736e0cd7a4d844/project/blocky_game/blocks/voxel_library.tres#L82
How are we going to use this?
"material_override_0 = ExtResource("**_2_r7axq_**")"
what does that mean and how can it be replicated by regular people?

Like how do we add blocks step by step to test?

Are those weird scrambled numbers and letter from a sort of 'easy' way of doing things or a compression system? I don't know what to do after reading the block documentation either?

https://voxel-tools.readthedocs.io/en/latest/api/VoxelBlockyLibrary/
https://voxel-tools.readthedocs.io/en/latest/specs/block_format_v4/
https://voxel-tools.readthedocs.io/en/latest/specs/instances_format_v1/
https://voxel-tools.readthedocs.io/en/latest/api/VoxelBlockyModel/
I read these these and like I get lost there's no direction is like endless specifications how does this all worth together? Is there a guide or something? My brain is spinning so fast because its trying to do all the directions at once because its like there's no guide or steps or like cook book. It feel like like baking cake but you don't get steps you get like the atomic detail of the flour how the flour can be used in a billion applications then its the same for the eggs the sugar the milk the oven specs the atomic structure of the quarks and the thermodynamics of the oven like mate we don't need literally ever single detail down to the atom. It's good but like how you have to mix the flour the eggs how much and where does it all combine? What to not do? What steps can regular people take to add more things to already working systems? So okay my brain is not having a good time for it just doesn't understand what to do next and how things combine to add more blocks in what order without thinking of 10,000 ways it could possibly work and like maybe 10 or 20 of those will work.

So this started with this:
var items = voxel_tool.get_voxel_metadata(chest_position)
items.append({"type": "arrows", "count": 64})
voxel_tool.set_voxel_metadata(chest_position, items)
https://github.com/Zylann/godot_voxel/issues/98#issue-548479598

It was like my monkey emotion brain went like this: Ah piece of chest just needs new block find how to make new block and add metadata to new block. Add block to inventory in a test clone iteration of blockygame, test over and over be dumb until it works then pretend to be smart got it 1st try.

So I'm lost lol how do we add the new blocks mate? Okay I will add the art for chest okay, it does not need animations its like mission 1 get new chest block and add meta data and test. How do we the add the blocks, my brain is not happy with the logic math parts because the documentation is lacking a guide for how to add blocks and I think the weird numbers and letters are strings that come spat out of a machine system to make big things small. I remember them from working on WoW databases and Baldur's Gate and Diablo and it needs a machine system / code to make it readable or like you process ew4ed54f56r45 and it says like 'line 6 column 4 crude shortsword'. I gotta think about this.

**Comment by WithinAmnesia** [comment]
![terrain(chest)](https://github.com/Zylann/godot_voxel/assets/86871191/c9c5f2b9-1603-4b93-bbbe-b7dc7844ef39)
Here is the prototype chest. It should be able to use with blanks texture and have the horizontal side facing the player with the latch.

**Comment by WithinAmnesia** [comment]
I messed up. I used the top not the side art 1 sec.

**Comment by AimiIsFat** [comment]
Excuse me, @WithinAmnesia, but could you please stop reporting all of your progress here? Many people are watching this project and we are here to view progress on __this__ project, not your own. _It is best to only post inside issues when you actually NEED help and can't figure it out on your own_, not to tell people about your unrelated project that has almost nothing to do with this one, as that is considered **spamming**, and is against GitHub ToS. There are better places to do that, and I'm tired of receiving random emails every 5 minutes because you want to talk about your project in a place that you shouldn't be.

**Comment by WithinAmnesia** [comment]
Okay @AimiIsFat maybe I should go and post more on the voxel_game / blockygame repo if I was in the wrong space to questions which I am not for this is on topic as much as it gets; I literally made chest assets today to help further this specific this topic voxel metadata. I disagree with your statement and opinion because I am asking legitimate questions that are in the right places and they need space and I need help at times too.

Also just because its annoying you does not mean it is spamming for there's no malicious or excessive posting but rather the opposite in that I am genuinely trying to develop more on what is here. As in specifically a general case use examples of voxel_metadata for not just myself but the community to use to make more than just my game example but for everyone's game too. For there are a lake of working examples for storage and entities; this would greatly help not just myself but you and the author and everyone who uses this to make a working game.

The author does not have time for random internet drama and this malarkey this stuff is HARD okay I don't ask willy nilly I test for hours and then when i am really stuck I ask for help mate. They are busy and said so consistently but I will not take any malarkey from the community without good reason of which this does not have any. This is a waste of time arguing and I wish I spent my time and other's time more productively reading my rebuttal but i will refute this charges and I will defend myself rightly.
The rest is in the gist (to save everyone from a wall of text): https://gist.github.com/WithinAmnesia/4863f10e66991e39f67b63eef9c6d931
Please I just want dev work here. I am sorry for any drama. I just want a nice place for everyone in the community.

**Comment by AimiIsFat** [comment]
@WithinAmnesia, I do get how you feel, but there is a bit you should know so I'll just elaborate on that one last time since you don't seem to understand it all the way. Also, it is fine to make another post when someone replies to you, just not making several posts when it is unnecessary.

Anyone else reading this, feel free to skip it, unless you just want some general tips on GitHub usage.

> I have separate issues that if I make a giant post about crammed together, it gets confusing for many people; including myself. Yet it just gets out of hand a super mega post with 20+ different questions solved and unsolved across 1-3 months. As like imagine a kitchen but you only have 1 breadboard worth of counter-space for everything.

There are 2 different solutions here. The first being to take it to the project's Discord, which is linked in the README. Not entirely sure what they do there since I'm not in it but typically project Discords are good for that if you are serious about helping. The second being to read over your posts before sending them. You can use that to see which information isn't important to send, how to format the post better, and ways to make it easier to read. If both fail, it might be a good idea to rewrite it from scratch. If you have that many questions, you may want to also get better at programming before trying to contribute, as messy or inefficient code will likely not be accepted into a project.

Also, if you write a big post with a lot of questions and they go unanswered, the issue is likely not the post. The issue is most likely that the project maintainer does not have time to answer them. In this case, you should probably give up. I do the same if I don't receive a reply. Posting in other places might annoy them enough to make them respond to you, but they likely won't be happy about it, even if they don't show it.

> Also I need to ask questions and speak.

You can, just keep it in one issue. People can unsubscribe from specific issues if they aren't interested, but posting on other issues means that people will have to go and manually unsubscribe from all of them, even if they might be otherwise interested in that issue. I would really have no problem if you just did that.

> This can be a messy process and I'd like for it to be neat but it can be messy. Yes posting a lot can look excessive. Yet also I have a lot of work to report and when I spend I think its now at least 20+ hours in ~3 days on this; I will find issues and somethings are not easy to solve.

It typically can be neat. You don't need to report your work until you send in a pull request. I recommend you view other issues and study how they're written.

> I wish there was a better way to talk with the main authour and not bug the 68 other people.

Discord. Otherwise, just keep it in one issue and follow the other tips.

> Also its natural to get new questions and puzzles when working a lot. For example I have made efforts to use the blockygame repo and ask specific questions to not be unnecessarily excessive or unpleasant on here. https://github.com/Zylann/voxelgame/issues/104 .

Though the writing is a bit messy, I think it is good that you tried that. However, you should've kept it in one issue. If the project maintainer doesn't respond then they likely don't have time for it or don't want to respond for some other reason. It is best to respect the project maintainer and let them answer when they want to, rather than trying to get their attention by posting elsewhere, even if this means that your questions never get answered, otherwise it is disrespectful. Project maintainers are (usually) volunteers, and are not obligated to answer everything you ask.

Anyways, that is all. I will refrain from further replies to avoid bothering the others watching this repository. Just keep the posts in one issue, thanks.

**Comment by WithinAmnesia** [comment]
How to add new blocks in the Blockygame demo that work in multiplayer solved: https://github.com/Zylann/voxelgame/issues/104#issuecomment-1963051690
Now onto voxel_metadata for storage and entity multiplayer testing.

**Comment by nonchip** [comment]
@WithinAmnesia so you learned nothing, great. since @Zylann didn't do the right thing and lock this issue yet, can you at least stop spamming everyone else with offtopic BOOKS? this is a 2020 issue about implementing voxel metadata that's been closed because it's NOT an issue anymore. AND has less than nothing to do with anything you said after Zylann answered your first round of *almost* related questions.
